import type { UnitId, VocabItem } from "../types";

type Bank = Partial<Record<UnitId, VocabItem[]>>;

/** ASL vocab keyed to https://www.signasl.org/sign/{signasl} */
function s(
  term: string,
  meaning: string,
  signasl: string,
  hint?: string,
): VocabItem {
  return { term, meaning, signasl, hint };
}

export const ASL_VOCAB: Bank = {
  grammar: [
    s("NOT", "Negation / deny", "not", "Often with a headshake"),
    s("QUESTION", "Ask a question", "question", "Furrowed or raised brows"),
    s("CLASSIFIER", "Handshape standing for a class of things", "classifier"),
    s("FINISH", "Done / completed aspect", "finish"),
    s("HAVE", "Possession / existence", "have"),
    s("BECAUSE", "Reason / cause", "because"),
  ],
  alphabet: [
    s("A", "Letter A (fingerspelling)", "a", "Closed fist, thumb alongside"),
    s("B", "Letter B (fingerspelling)", "b", "Flat hand, thumb across"),
    s("C", "Letter C (fingerspelling)", "c", "Curved C handshape"),
    s("FINGERSPELL", "Spell letter by letter", "fingerspell"),
    s("NAME", "Name / name sign context", "name"),
    s("ALPHABET", "The fingerspelling alphabet", "alphabet"),
  ],
  pronouns: [
    s("ME", "I / me", "me", "Point to yourself"),
    s("YOU", "You", "you", "Point to the person"),
    s("HE", "He / him (pointing)", "he"),
    s("SHE", "She / her (pointing)", "she"),
    s("WE", "We / us", "we"),
    s("THEY", "They / them", "they"),
  ],
  nouns: [
    s("PERSON", "Person / human", "person"),
    s("HOME", "Home / house where you live", "home"),
    s("SCHOOL", "School", "school"),
    s("NAME", "Name", "name"),
    s("WATER", "Water", "water"),
    s("BOOK", "Book", "book"),
  ],
  verbs: [
    s("GO", "Go", "go"),
    s("COME", "Come", "come"),
    s("WANT", "Want", "want"),
    s("NEED", "Need", "need"),
    s("LIKE", "Like", "like"),
    s("HELP", "Help", "help"),
  ],
  adjectives: [
    s("BIG", "Big / large", "big"),
    s("SMALL", "Small / little", "small"),
    s("GOOD", "Good", "good"),
    s("BAD", "Bad", "bad"),
    s("FAST", "Fast / quick", "fast"),
    s("SLOW", "Slow", "slow"),
  ],
  colors: [
    s("RED", "Red", "red"),
    s("BLUE", "Blue", "blue"),
    s("GREEN", "Green", "green"),
    s("YELLOW", "Yellow", "yellow"),
    s("BLACK", "Black", "black"),
    s("WHITE", "White", "white"),
  ],
  maths: [
    s("ONE", "Number one", "one"),
    s("TWO", "Number two", "two"),
    s("THREE", "Number three", "three"),
    s("FIVE", "Number five", "five"),
    s("TEN", "Number ten", "ten"),
    s("PLUS", "Plus / add", "plus"),
  ],
  time: [
    s("NOW", "Now", "now"),
    s("TOMORROW", "Tomorrow", "tomorrow"),
    s("YESTERDAY", "Yesterday", "yesterday"),
    s("WEEK", "Week", "week"),
    s("MONTH", "Month", "month"),
    s("TIME", "Time", "time"),
  ],
  emotions: [
    s("HAPPY", "Happy", "happy"),
    s("SAD", "Sad", "sad"),
    s("ANGRY", "Angry", "angry"),
    s("SCARED", "Scared / afraid", "scared"),
    s("LOVE", "Love", "love"),
    s("EXCITED", "Excited", "excited"),
  ],
  body: [
    s("HEAD", "Head", "head"),
    s("EYE", "Eye", "eye"),
    s("HAND", "Hand", "hand"),
    s("HEART", "Heart", "heart"),
    s("LEG", "Leg", "leg"),
    s("EAR", "Ear", "ear"),
  ],
  senses: [
    s("SEE", "See", "see"),
    s("HEAR", "Hear", "hear"),
    s("TOUCH", "Touch", "touch"),
    s("SMELL", "Smell", "smell"),
    s("TASTE", "Taste", "taste"),
    s("FEEL", "Feel", "feel"),
  ],
  clothing: [
    s("SHIRT", "Shirt", "shirt"),
    s("PANTS", "Pants", "pants"),
    s("SHOES", "Shoes", "shoes"),
    s("HAT", "Hat", "hat"),
    s("COAT", "Coat / jacket", "coat"),
    s("GLASSES", "Glasses", "glasses"),
  ],
  food: [
    s("EAT", "Eat / food", "eat"),
    s("DRINK", "Drink", "drink"),
    s("BREAD", "Bread", "bread"),
    s("MILK", "Milk", "milk"),
    s("APPLE", "Apple", "apple"),
    s("COFFEE", "Coffee", "coffee"),
  ],
  animals: [
    s("DOG", "Dog", "dog"),
    s("CAT", "Cat", "cat"),
    s("BIRD", "Bird", "bird"),
    s("FISH", "Fish", "fish"),
    s("HORSE", "Horse", "horse"),
    s("COW", "Cow", "cow"),
  ],
  furniture: [
    s("CHAIR", "Chair", "chair"),
    s("TABLE", "Table", "table"),
    s("BED", "Bed", "bed"),
    s("DOOR", "Door", "door"),
    s("WINDOW", "Window", "window"),
    s("LAMP", "Lamp", "lamp"),
  ],
  occupations: [
    s("TEACHER", "Teacher", "teacher"),
    s("DOCTOR", "Doctor", "doctor"),
    s("NURSE", "Nurse", "nurse"),
    s("POLICE", "Police", "police"),
    s("COOK", "Cook / chef", "cook"),
    s("ARTIST", "Artist", "artist"),
  ],
  school: [
    s("STUDENT", "Student", "student"),
    s("CLASS", "Class", "class"),
    s("HOMEWORK", "Homework", "homework"),
    s("TEST", "Test / exam", "test"),
    s("QUESTION", "Question", "question"),
    s("ANSWER", "Answer", "answer"),
  ],
  travel: [
    s("WHERE", "Where", "where"),
    s("HERE", "Here", "here"),
    s("LEFT", "Left", "left"),
    s("RIGHT", "Right", "right"),
    s("AIRPLANE", "Airplane", "airplane"),
    s("TRAIN", "Train", "train"),
  ],
  countries: [
    s("AMERICA", "America / USA", "america"),
    s("ENGLAND", "England", "england"),
    s("CHINA", "China", "china"),
    s("SPAIN", "Spain", "spain"),
    s("FRANCE", "France", "france"),
    s("CANADA", "Canada", "canada"),
  ],
  culture: [
    s("DEAF", "Deaf", "deaf"),
    s("HEARING", "Hearing (person)", "hearing"),
    s("CULTURE", "Culture", "culture"),
    s("COMMUNITY", "Community", "community"),
    s("TRADITION", "Tradition", "tradition"),
    s("RESPECT", "Respect", "respect"),
  ],
  medical: [
    s("HOSPITAL", "Hospital", "hospital"),
    s("PAIN", "Pain / hurt", "pain"),
    s("MEDICINE", "Medicine", "medicine"),
    s("SICK", "Sick", "sick"),
    s("HEALTHY", "Healthy", "healthy"),
    s("EMERGENCY", "Emergency", "emergency"),
  ],
  politics: [
    s("VOTE", "Vote", "vote"),
    s("LAW", "Law", "law"),
    s("GOVERNMENT", "Government", "government"),
    s("RIGHTS", "Rights", "rights"),
    s("PEACE", "Peace", "peace"),
    s("EQUAL", "Equal / equality", "equal"),
  ],
  technology: [
    s("COMPUTER", "Computer", "computer"),
    s("PHONE", "Phone", "phone"),
    s("INTERNET", "Internet", "internet"),
    s("EMAIL", "Email", "email"),
    s("VIDEO", "Video", "video"),
    s("PASSWORD", "Password", "password"),
  ],
  psychology: [
    s("MIND", "Mind", "mind"),
    s("THINK", "Think", "think"),
    s("REMEMBER", "Remember", "remember"),
    s("FORGET", "Forget", "forget"),
    s("STRESS", "Stress", "stress"),
    s("CALM", "Calm", "calm"),
  ],
  speaking: [
    s("HELLO", "Hello", "hello"),
    s("THANK-YOU", "Thank you", "thank-you"),
    s("PLEASE", "Please", "please"),
    s("SORRY", "Sorry", "sorry"),
    s("YES", "Yes", "yes"),
    s("NO", "No", "no"),
  ],
  reading: [
    s("READ", "Read", "read"),
    s("STORY", "Story", "story"),
    s("SENTENCE", "Sentence", "sentence"),
    s("WORD", "Word", "word"),
    s("TITLE", "Title", "title"),
    s("BOOK", "Book", "book"),
  ],
  writing: [
    s("WRITE", "Write", "write"),
    s("LETTER", "Letter", "letter"),
    s("LIST", "List", "list"),
    s("NOTE", "Note", "note"),
    s("PAPER", "Paper", "paper"),
    s("PEN", "Pen", "pen"),
  ],
  translating: [
    s("INTERPRET", "Interpret", "interpret"),
    s("MEANING", "Meaning", "meaning"),
    s("SAME", "Same", "same"),
    s("DIFFERENT", "Different", "different"),
    s("EXAMPLE", "Example", "example"),
    s("COMPARE", "Compare", "compare"),
  ],
  slang: [
    s("WHATEVER", "Whatever (dismissive)", "whatever", "Informal"),
    s("COOL", "Cool / awesome", "cool"),
    s("GROSS", "Gross / disgusting", "gross"),
    s("DUMB", "Dumb (insulting — avoid)", "dumb", "Rude"),
    s("SHUT-UP", "Shut up (rude)", "shut-up", "Rude — use carefully"),
    s("OH-I-SEE", "Oh I see / understanding", "oh-i-see"),
  ],
  quotes: [
    s("PRACTICE", "Practice", "practice"),
    s("LEARN", "Learn", "learn"),
    s("DEAF", "Deaf (identity / community)", "deaf"),
    s("RESPECT", "Respect", "respect"),
    s("TOGETHER", "Together", "together"),
    s("IMPORTANT", "Important", "important"),
  ],
  media: [
    s("MOVIE", "Movie / film", "movie"),
    s("TELEVISION", "Television / TV", "television"),
    s("BOOK", "Book", "book"),
    s("ACTOR", "Actor", "actor"),
    s("MUSIC", "Music", "music"),
    s("SUBTITLE", "Subtitle / caption", "subtitle"),
  ],
};
