import type { LanguageId, UnitId, VocabItem } from "../types";

type ExtraBank = Partial<Record<UnitId, VocabItem[]>>;

function v(
  term: string,
  meaning: string,
  extras?: Partial<VocabItem>,
): VocabItem {
  return { term, meaning, ...extras };
}

/** Specialty-unit vocab that only applies to matching languages. */
export const EXTRA_VOCAB: Partial<Record<LanguageId, ExtraBank>> = {
  asl: {
    handshapes: [
      v("CL:1", "Person / thin upright object classifier", { signasl: "classifier", cefr: "A1" }),
      v("CL:3", "Vehicle classifier", { signasl: "car", cefr: "A1" }),
      v("CL:5", "Large flat object / crowd", { signasl: "classifier", cefr: "A2" }),
      v("CL:C", "Cup / cylindrical object", { signasl: "cup", cefr: "A2" }),
      v("CL:B", "Flat surface / wall", { signasl: "classifier", cefr: "B1" }),
      v("CL:V", "Legs / look", { signasl: "see", cefr: "B1" }),
      v("Bent-V", "Crouched person / animal", { signasl: "person", cefr: "B2" }),
      v("Open-8", "Sensitive touch / emotion", { signasl: "feel", cefr: "C1" }),
    ],
    nonmanuals: [
      v("Raised brows", "Yes/no questions", { signasl: "question", cefr: "A1" }),
      v("Furrowed brows", "WH-questions", { signasl: "what", cefr: "A1" }),
      v("Headshake", "Negation with NOT", { signasl: "not", cefr: "A1" }),
      v("Head nod", "Affirmation", { signasl: "yes", cefr: "A2" }),
      v("Mouth morpheme CHA", "Very large / huge", { signasl: "big", cefr: "B1" }),
      v("Mouth morpheme OO", "Small / thin", { signasl: "small", cefr: "B1" }),
      v("Eye gaze", "Agreement / role shift cue", { signasl: "see", cefr: "B2" }),
      v("Shoulder shift", "Contrast two referents", { signasl: "compare", cefr: "C1" }),
    ],
    deafculture: [
      v("Deaf", "Cultural / linguistic identity", { signasl: "deaf", cefr: "A1" }),
      v("Hearing", "Non-Deaf person", { signasl: "hearing", cefr: "A1" }),
      v("Sign", "Use signed language", { signasl: "sign", cefr: "A1" }),
      v("Interpreter", "Professional language bridge", { signasl: "interpreter", cefr: "A2" }),
      v("Deaf club", "Community gathering space", { signasl: "club", cefr: "B1" }),
      v("Name sign", "Personal sign name", { signasl: "name", cefr: "B1" }),
      v("Deaf gain", "Cultural benefits of Deaf ways", { signasl: "deaf", cefr: "B2" }),
      v("Audism", "Discrimination based on hearing status", { signasl: "discrimination", cefr: "C1" }),
    ],
  },
  bsl: {
    handshapes: [
      v("CL:person", "Person moving in space", { signbsl: "person", cefr: "A1" }),
      v("CL:vehicle", "Vehicle path", { signbsl: "car", cefr: "A1" }),
      v("CL:flat", "Flat surfaces", { signbsl: "table", cefr: "A2" }),
      v("CL:round", "Round objects", { signbsl: "ball", cefr: "A2" }),
      v("CL:legs", "Two-legged movement", { signbsl: "walk", cefr: "B1" }),
      v("Handling CL", "How the hand holds an object", { signbsl: "hold", cefr: "B2" }),
      v("SASS", "Size and shape specifier", { signbsl: "big", cefr: "C1" }),
    ],
    nonmanuals: [
      v("Raised brows", "Yes/no questions", { signbsl: "question", cefr: "A1" }),
      v("Furrowed brows", "WH-questions", { signbsl: "what", cefr: "A1" }),
      v("Headshake", "Negation", { signbsl: "not", cefr: "A1" }),
      v("Puffed cheeks", "Large amount / intensity", { signbsl: "big", cefr: "A2" }),
      v("Tongue thin", "Careful / precise", { signbsl: "careful", cefr: "B1" }),
      v("Role shift gaze", "Take another’s viewpoint", { signbsl: "look", cefr: "B2" }),
    ],
    deafculture: [
      v("Deaf", "Deaf identity", { signbsl: "deaf", cefr: "A1" }),
      v("BSL", "British Sign Language", { signbsl: "bsl", cefr: "A1" }),
      v("Hearing", "Hearing person", { signbsl: "hearing", cefr: "A1" }),
      v("Interpreter", "Language interpreter", { signbsl: "interpreter", cefr: "A2" }),
      v("Deaf school", "School for Deaf students", { signbsl: "school", cefr: "B1" }),
      v("Finger spell", "British two-handed alphabet", { signbsl: "fingerspell", cefr: "B1" }),
      v("Deaf pride", "Pride in Deaf culture", { signbsl: "proud", cefr: "B2" }),
    ],
  },
  isl: {
    handshapes: [
      v("CL:person", "Person classifier", { cefr: "A1" }),
      v("CL:vehicle", "Vehicle classifier", { cefr: "A1" }),
      v("CL:flat", "Flat object", { cefr: "A2" }),
      v("Pointing", "Index referents in space", { cefr: "A1" }),
      v("Handling", "Handle-shaped classifiers", { cefr: "B1" }),
      v("SASS", "Size-and-shape specifiers", { cefr: "B2" }),
    ],
    nonmanuals: [
      v("Raised brows", "Yes/no or topic marking", { cefr: "A1" }),
      v("Furrowed brows", "WH content questions", { cefr: "A1" }),
      v("Headshake", "Negation", { cefr: "A1" }),
      v("Mouthing", "Optional spoken mouth patterns", { cefr: "A2" }),
      v("Body shift", "Contrast or role", { cefr: "B1" }),
    ],
    deafculture: [
      v("International Sign", "Contact signing at global events", { cefr: "A1" }),
      v("Deaf", "Deaf identity across countries", { cefr: "A1" }),
      v("WFD", "World Federation of the Deaf", { cefr: "B1" }),
      v("Interpreter", "Conference interpreter", { cefr: "A2" }),
      v("Deaf space", "Designed for visual access", { cefr: "B2" }),
    ],
  },
  nzsl: {
    handshapes: [
      v("CL:person", "Person moving", { nzsl: "4446", cefr: "A1" }),
      v("CL:vehicle", "Vehicle path", { nzsl: "car", cefr: "A1" }),
      v("CL:flat", "Flat surface", { nzsl: "523", cefr: "A2" }),
      v("Pointing", "Establish referents", { nzsl: "2321", cefr: "A1" }),
      v("Handling CL", "How objects are held", { cefr: "B1" }),
      v("SASS", "Size and shape", { cefr: "B2" }),
    ],
    nonmanuals: [
      v("Raised brows", "Yes/no questions", { nzsl: "6010", cefr: "A1" }),
      v("Furrowed brows", "WH-questions", { nzsl: "2266", cefr: "A1" }),
      v("Headshake", "Negation", { nzsl: "3127", cefr: "A1" }),
      v("Head nod", "Affirmation", { nzsl: "3236", cefr: "A2" }),
      v("Role shift", "Report another’s signing", { cefr: "B1" }),
    ],
    deafculture: [
      v("Deaf", "Deaf identity in Aotearoa", { nzsl: "deaf", cefr: "A1" }),
      v("NZSL", "New Zealand Sign Language", { cefr: "A1" }),
      v("Māori Deaf", "Tāngata turi Māori community", { nzsl: "3204", cefr: "A2" }),
      v("Interpreter", "NZSL interpreter", { nzsl: "3063", cefr: "A2" }),
      v("Deaf club", "Community hub", { cefr: "B1" }),
      v("Official language", "NZSL is an official language", { cefr: "B2" }),
    ],
  },
  mandarin: {
    tones: [
      v("第一声", "First tone — high level ˉ", { romanization: "dì-yī shēng", cefr: "A1" }),
      v("第二声", "Second tone — rising ˊ", { romanization: "dì-èr shēng", cefr: "A1" }),
      v("第三声", "Third tone — low dipping ˇ", { romanization: "dì-sān shēng", cefr: "A1" }),
      v("第四声", "Fourth tone — falling ˋ", { romanization: "dì-sì shēng", cefr: "A1" }),
      v("轻声", "Neutral tone", { romanization: "qīngshēng", cefr: "A2" }),
      v("妈 / 麻 / 马 / 骂", "mā má mǎ mà tone minimal set", { romanization: "ma", cefr: "A2" }),
      v("Tone sandhi", "第三声 changes before another 3rd", { romanization: "biàndiào", cefr: "B1" }),
      v("Tone pair drill", "Practice two-syllable tone combos", { cefr: "B2" }),
    ],
    characters: [
      v("汉字", "Chinese character", { romanization: "hànzì", cefr: "A1" }),
      v("部首", "Radical", { romanization: "bùshǒu", cefr: "A1" }),
      v("笔画", "Stroke", { romanization: "bǐhuà", cefr: "A1" }),
      v("人", "Person radical / character", { romanization: "rén", cefr: "A2" }),
      v("水", "Water radical", { romanization: "shuǐ", cefr: "A2" }),
      v("拼音", "Pinyin romanization", { romanization: "pīnyīn", cefr: "A1" }),
      v("简体 / 繁体", "Simplified vs traditional", { romanization: "jiǎntǐ / fántǐ", cefr: "B1" }),
      v("形声字", "Phono-semantic compound", { romanization: "xíngshēngzì", cefr: "B2" }),
    ],
    measurewords: [
      v("个", "General measure word", { romanization: "gè", cefr: "A1" }),
      v("本", "For books", { romanization: "běn", cefr: "A1" }),
      v("只", "For many animals", { romanization: "zhī", cefr: "A2" }),
      v("条", "Long thin things", { romanization: "tiáo", cefr: "A2" }),
      v("张", "Flat things", { romanization: "zhāng", cefr: "A2" }),
      v("杯", "Cups of liquid", { romanization: "bēi", cefr: "A1" }),
      v("件", "Clothes / matters", { romanization: "jiàn", cefr: "B1" }),
      v("辆", "Vehicles", { romanization: "liàng", cefr: "B1" }),
    ],
  },
  latin: {
    cases: [
      v("nominative", "Subject of the verb", { cefr: "A1", hint: "puella cantat" }),
      v("accusative", "Direct object", { cefr: "A1", hint: "puellam video" }),
      v("genitive", "Possession / of", { cefr: "A2", hint: "liber puellae" }),
      v("dative", "Indirect object / to-for", { cefr: "A2", hint: "puellae do" }),
      v("ablative", "By / with / from", { cefr: "B1", hint: "gladio" }),
      v("vocative", "Direct address", { cefr: "B1", hint: "O amice!" }),
      v("locative", "Place where (select nouns)", { cefr: "B2", hint: "Romae" }),
      v("case agreement", "Adjectives match noun case", { cefr: "C1" }),
    ],
    declensions: [
      v("1st declension", "Mostly -a stems (puella)", { cefr: "A1" }),
      v("2nd declension", "-us / -um stems (servus, bellum)", { cefr: "A1" }),
      v("3rd declension", "Mixed consonant / i-stems", { cefr: "A2" }),
      v("4th declension", "-us stems (manus, exercitus)", { cefr: "B1" }),
      v("5th declension", "-es stems (res, dies)", { cefr: "B1" }),
      v("neuter rule", "Nom = acc in neuter plurals", { cefr: "A2" }),
      v("i-stem", "Special 3rd declension gen. pl. -ium", { cefr: "B2" }),
    ],
    conjugations: [
      v("1st conjugation", "-āre verbs (amo, amare)", { cefr: "A1" }),
      v("2nd conjugation", "-ēre verbs (moneo)", { cefr: "A1" }),
      v("3rd conjugation", "-ere verbs (rego)", { cefr: "A2" }),
      v("4th conjugation", "-īre verbs (audio)", { cefr: "A2" }),
      v("sum / esse", "Irregular “to be”", { cefr: "A1" }),
      v("perfect stem", "Completed aspect forms", { cefr: "B1" }),
      v("passive voice", "Patient as subject", { cefr: "B2" }),
      v("subjunctive", "Wish / purpose / cum clauses", { cefr: "C1" }),
    ],
  },
  spanish: {
    serestar: [
      v("ser", "Essence, identity, origin, time", { cefr: "A1", hint: "Soy estudiante" }),
      v("estar", "State, location, progressive", { cefr: "A1", hint: "Estoy cansado" }),
      v("soy / estoy", "I am (essence vs state)", { cefr: "A1" }),
      v("es / está", "He/she/it is", { cefr: "A1" }),
      v("permanent vs temporary", "Guide for choosing ser/estar", { cefr: "A2" }),
      v("estar + participle", "Resulting state", { cefr: "B1", hint: "La puerta está abierta" }),
      v("ser + participle", "Passive event", { cefr: "B2", hint: "Fue construido" }),
      v("Adjectives that shift", "listo, verde, etc. change meaning", { cefr: "C1" }),
    ],
    formality: [
      v("tú", "Informal singular you", { cefr: "A1" }),
      v("usted", "Formal singular you", { cefr: "A1" }),
      v("vosotros", "Informal plural (Spain)", { cefr: "A2" }),
      v("ustedes", "Plural you ( LatAm / formal Spain)", { cefr: "A1" }),
      v("don / doña", "Respectful titles", { cefr: "B1" }),
      v("T-V distinction", "Choosing tú vs usted", { cefr: "B1" }),
      v("vos", "Informal you in parts of LatAm", { cefr: "B2" }),
    ],
    subjunctive: [
      v("quiero que + subj.", "Desire triggers subjunctive", { cefr: "B1", hint: "Quiero que vengas" }),
      v("espero que", "Hope + subjunctive", { cefr: "B1" }),
      v("es importante que", "Value judgment + subjunctive", { cefr: "B2" }),
      v("cuando + subj.", "Future time clause", { cefr: "B2", hint: "Cuando llegues…" }),
      v("present subjunctive", "-e / -a endings", { cefr: "B1" }),
      v("imperfect subjunctive", "-ra / -se forms", { cefr: "C1" }),
      v("ojalá", "Strong wish", { cefr: "B2" }),
    ],
  },
  dutch: {
    dutcharticles: [
      v("de", "Common gender article", { cefr: "A1", hint: "de man, de vrouw" }),
      v("het", "Neuter gender article", { cefr: "A1", hint: "het huis, het kind" }),
      v("een", "Indefinite a/an", { cefr: "A1" }),
      v("de plural", "All plurals take de", { cefr: "A2", hint: "de huizen" }),
      v("het diminutive", "Most -je words are het", { cefr: "A2", hint: "het huisje" }),
      v("article + adjective", "Agreement patterns", { cefr: "B1" }),
      v("lexical gender", "Memorize de/het with the noun", { cefr: "B1" }),
    ],
    separable: [
      v("opstaan", "to get up → Ik sta op", { cefr: "A2" }),
      v("aankomen", "to arrive → De trein komt aan", { cefr: "A2" }),
      v("meebrengen", "to bring along", { cefr: "A2" }),
      v("Prefix at end", "Main clause: finite verb #2, prefix last", { cefr: "A2" }),
      v("Subordinate cluster", "In dat-clauses prefixes stay with infinitive", { cefr: "B1" }),
      v("Particle vs prefix", "Stressed separable particles", { cefr: "B2" }),
      v("uitnodigen", "to invite", { cefr: "B1" }),
    ],
  },
  maori: {
    particles: [
      v("kei te", "Present continuous", { cefr: "A1", hint: "Kei te kai au" }),
      v("i", "Past tense marker", { cefr: "A1", hint: "I haere au" }),
      v("ka", "Future / narrative", { cefr: "A1", hint: "Ka kite" }),
      v("kua", "Perfect / completed", { cefr: "A2" }),
      v("e … ana", "Continuous (alternate)", { cefr: "A2" }),
      v("me", "Should / obligation", { cefr: "B1" }),
      v("kia", "Desire / purpose", { cefr: "B1" }),
      v("ai", "Relative / habitual particle", { cefr: "B2" }),
    ],
    pepeha: [
      v("ko … au", "I am … (name)", { cefr: "A1" }),
      v("tōku maunga", "My mountain", { cefr: "A2" }),
      v("tōku awa", "My river", { cefr: "A2" }),
      v("tōku waka", "My canoe / migration canoe", { cefr: "A2" }),
      v("tōku iwi", "My tribe", { cefr: "A2" }),
      v("tōku hapū", "My sub-tribe", { cefr: "B1" }),
      v("tōku marae", "My marae", { cefr: "B1" }),
      v("nō … au", "I am from …", { cefr: "A1" }),
    ],
    marae: [
      v("marae", "Sacred courtyard / complex", { cefr: "A1" }),
      v("wharenui", "Meeting house", { cefr: "A1" }),
      v("pōwhiri", "Welcome ceremony", { cefr: "A2" }),
      v("tangata whenua", "Home people / hosts", { cefr: "A2" }),
      v("manuhiri", "Guests / visitors", { cefr: "A2" }),
      v("karanga", "Ceremonial call", { cefr: "B1" }),
      v("whaikōrero", "Formal speechmaking", { cefr: "B1" }),
      v("hongi", "Pressing noses in greeting", { cefr: "A2" }),
      v("tikanga", "Correct procedure / custom", { cefr: "B2" }),
    ],
  },
};
