import type { CefrLevel, LanguageId } from "../types";

export type GrammarSentence = {
  id: string;
  cefr: CefrLevel;
  /** Word-order pattern name */
  pattern: string;
  /** How the pattern works */
  rule: string;
  /** English gloss / meaning */
  english: string;
  /** Tokens in the correct order */
  tokens: string[];
  note?: string;
};

/**
 * Sentence banks that teach arranging words (or glosses) in the right order.
 * Signed languages use topic–comment / time-topic-comment gloss order.
 */
export const GRAMMAR_SENTENCES: Record<LanguageId, GrammarSentence[]> = {
  spanish: [
    {
      id: "es-a1-1",
      cefr: "A1",
      pattern: "SVO",
      rule: "Spanish usually puts Subject → Verb → Object.",
      english: "I eat bread",
      tokens: ["Yo", "como", "pan"],
    },
    {
      id: "es-a1-2",
      cefr: "A1",
      pattern: "SVO",
      rule: "Keep the subject first, then the verb, then what it acts on.",
      english: "She drinks water",
      tokens: ["Ella", "bebe", "agua"],
    },
    {
      id: "es-a1-3",
      cefr: "A1",
      pattern: "Negation",
      rule: "Put no right before the verb.",
      english: "I do not want coffee",
      tokens: ["Yo", "no", "quiero", "café"],
    },
    {
      id: "es-a2-1",
      cefr: "A2",
      pattern: "Questions",
      rule: "Yes/no questions often keep SVO and add ¿ … ?",
      english: "Do you speak Spanish?",
      tokens: ["¿", "Hablas", "español", "?"],
    },
    {
      id: "es-a2-2",
      cefr: "A2",
      pattern: "Adjective after noun",
      rule: "Most descriptive adjectives follow the noun.",
      english: "a red house",
      tokens: ["una", "casa", "roja"],
    },
    {
      id: "es-b1-1",
      cefr: "B1",
      pattern: "Object pronouns",
      rule: "Clitic object pronouns usually sit before a conjugated verb.",
      english: "I see her",
      tokens: ["Yo", "la", "veo"],
    },
    {
      id: "es-b1-2",
      cefr: "B1",
      pattern: "Past (pretérito)",
      rule: "Still SVO — only the verb ending shows past tense.",
      english: "We bought a book",
      tokens: ["Nosotros", "compramos", "un", "libro"],
    },
    {
      id: "es-b2-1",
      cefr: "B2",
      pattern: "Relative clause",
      rule: "que links the noun to the clause that describes it.",
      english: "the book that I read",
      tokens: ["el", "libro", "que", "leí"],
    },
    {
      id: "es-c1-1",
      cefr: "C1",
      pattern: "Subjunctive trigger",
      rule: "After quiero que, the next clause uses subjunctive order (still SVO).",
      english: "I want you to come",
      tokens: ["Quiero", "que", "vengas"],
    },
    {
      id: "es-c2-1",
      cefr: "C2",
      pattern: "Focus fronting",
      rule: "You can front an object for emphasis, then restore the rest.",
      english: "That book, I already read",
      tokens: ["Ese", "libro", "ya", "lo", "leí"],
    },
  ],

  dutch: [
    {
      id: "nl-a1-1",
      cefr: "A1",
      pattern: "SVO",
      rule: "Main clauses often start Subject → Verb → Object.",
      english: "I eat bread",
      tokens: ["Ik", "eet", "brood"],
    },
    {
      id: "nl-a1-2",
      cefr: "A1",
      pattern: "V2",
      rule: "The finite verb stays in second position — even if time comes first.",
      english: "Today I eat bread",
      tokens: ["Vandaag", "eet", "ik", "brood"],
      note: "Time first → verb still second → then subject.",
    },
    {
      id: "nl-a2-1",
      cefr: "A2",
      pattern: "geen",
      rule: "Use geen before a noun to mean “no / not a”.",
      english: "I eat no bread",
      tokens: ["Ik", "eet", "geen", "brood"],
    },
    {
      id: "nl-a2-2",
      cefr: "A2",
      pattern: "Separable verb",
      rule: "The prefix of a separable verb often moves to the end.",
      english: "I get up",
      tokens: ["Ik", "sta", "op"],
    },
    {
      id: "nl-b1-1",
      cefr: "B1",
      pattern: "Subordinate SOV",
      rule: "After omdat, the conjugated verb goes to the end.",
      english: "because I eat bread",
      tokens: ["omdat", "ik", "brood", "eet"],
    },
    {
      id: "nl-b1-2",
      cefr: "B1",
      pattern: "V2 question",
      rule: "Yes/no questions put the verb first.",
      english: "Do you speak Dutch?",
      tokens: ["Spreek", "je", "Nederlands"],
    },
    {
      id: "nl-b2-1",
      cefr: "B2",
      pattern: "Perfect + participle end",
      rule: "In perfect tense, the participle usually comes last.",
      english: "I have bought a book",
      tokens: ["Ik", "heb", "een", "boek", "gekocht"],
    },
    {
      id: "nl-c1-1",
      cefr: "C1",
      pattern: "Nested clause",
      rule: "Each subordinating conjunction pushes its verb further right.",
      english: "I think that she is coming today",
      tokens: ["Ik", "denk", "dat", "ze", "vandaag", "komt"],
    },
    {
      id: "nl-c2-1",
      cefr: "C2",
      pattern: "V2 with long front",
      rule: "Even a long fronted phrase counts as position 1 — verb still #2.",
      english: "After the meeting I go home",
      tokens: ["Na", "de", "vergadering", "ga", "ik", "naar", "huis"],
    },
  ],

  mandarin: [
    {
      id: "zh-a1-1",
      cefr: "A1",
      pattern: "SVO",
      rule: "Mandarin is Subject → Verb → Object.",
      english: "I love you",
      tokens: ["我", "爱", "你"],
      note: "wǒ ài nǐ",
    },
    {
      id: "zh-a1-2",
      cefr: "A1",
      pattern: "Time before verb",
      rule: "Time words usually come before the verb (often after the subject).",
      english: "I eat today",
      tokens: ["我", "今天", "吃"],
      note: "wǒ jīntiān chī",
    },
    {
      id: "zh-a1-3",
      cefr: "A1",
      pattern: "吗 question",
      rule: "Add 吗 at the end for a yes/no question — keep the statement order.",
      english: "Are you good / How are you?",
      tokens: ["你", "好", "吗"],
      note: "nǐ hǎo ma",
    },
    {
      id: "zh-a2-1",
      cefr: "A2",
      pattern: "的 possessive",
      rule: "Possessor + 的 + noun.",
      english: "my book",
      tokens: ["我", "的", "书"],
      note: "wǒ de shū",
    },
    {
      id: "zh-a2-2",
      cefr: "A2",
      pattern: "了 completion",
      rule: "了 often follows the verb to mark a completed action.",
      english: "I ate",
      tokens: ["我", "吃", "了"],
      note: "wǒ chī le",
    },
    {
      id: "zh-b1-1",
      cefr: "B1",
      pattern: "Measure word",
      rule: "Number + measure word + noun.",
      english: "one person",
      tokens: ["一", "个", "人"],
      note: "yī ge rén",
    },
    {
      id: "zh-b1-2",
      cefr: "B1",
      pattern: "把 disposal",
      rule: "Subject + 把 + object + verb (object moved before the verb).",
      english: "I put the book on the table",
      tokens: ["我", "把", "书", "放", "在", "桌子", "上"],
    },
    {
      id: "zh-b2-1",
      cefr: "B2",
      pattern: "Coverb 在",
      rule: "Location with 在 comes before the main verb.",
      english: "I study at school",
      tokens: ["我", "在", "学校", "学习"],
    },
    {
      id: "zh-c1-1",
      cefr: "C1",
      pattern: "Topic–comment",
      rule: "A topic can come first; the comment follows.",
      english: "As for that book, I already read it",
      tokens: ["那", "本", "书", "我", "已经", "看", "了"],
    },
    {
      id: "zh-c2-1",
      cefr: "C2",
      pattern: "是…的 focus",
      rule: "是…的 frames known events to highlight details.",
      english: "It was yesterday that I arrived",
      tokens: ["我", "是", "昨天", "到", "的"],
    },
  ],

  maori: [
    {
      id: "mi-a1-1",
      cefr: "A1",
      pattern: "VSO tendency",
      rule: "Māori often puts the verb phrase before the subject.",
      english: "I am eating",
      tokens: ["Kei", "te", "kai", "au"],
    },
    {
      id: "mi-a1-2",
      cefr: "A1",
      pattern: "Past i",
      rule: "i marks past before the verb; subject still often follows.",
      english: "I ate",
      tokens: ["I", "kai", "au"],
    },
    {
      id: "mi-a2-1",
      cefr: "A2",
      pattern: "Article te",
      rule: "te comes before a singular noun.",
      english: "the book",
      tokens: ["te", "pukapuka"],
    },
    {
      id: "mi-a2-2",
      cefr: "A2",
      pattern: "Future ka",
      rule: "ka often starts future / narrative verb phrases.",
      english: "I will go",
      tokens: ["Ka", "haere", "au"],
    },
    {
      id: "mi-b1-1",
      cefr: "B1",
      pattern: "Location kei",
      rule: "kei + place can lead; the subject follows.",
      english: "I am at school",
      tokens: ["Kei", "te", "kura", "au"],
    },
    {
      id: "mi-b1-2",
      cefr: "B1",
      pattern: "Possessive tō / taku",
      rule: "Possessives usually sit before the noun.",
      english: "my friend",
      tokens: ["taku", "hoa"],
    },
    {
      id: "mi-b2-1",
      cefr: "B2",
      pattern: "Negation kāore",
      rule: "kāore comes first, then the rest of the clause.",
      english: "I am not going",
      tokens: ["Kāore", "au", "e", "haere"],
    },
    {
      id: "mi-c1-1",
      cefr: "C1",
      pattern: "Actor emphatic",
      rule: "Front the actor with ko for emphasis, then the verb phrase.",
      english: "It is I who am going",
      tokens: ["Ko", "au", "e", "haere", "ana"],
    },
    {
      id: "mi-c2-1",
      cefr: "C2",
      pattern: "Complex VSO",
      rule: "Keep tense/aspect markers with the verb before the subject and object.",
      english: "The children are reading the book",
      tokens: ["Kei", "te", "pānui", "ngā", "tamariki", "i", "te", "pukapuka"],
    },
  ],

  latin: [
    {
      id: "la-a1-1",
      cefr: "A1",
      pattern: "SOV tendency",
      rule: "Classical Latin often ends with the verb.",
      english: "The girl reads a book",
      tokens: ["Puella", "librum", "legit"],
    },
    {
      id: "la-a1-2",
      cefr: "A1",
      pattern: "Nominative + verb",
      rule: "Subject is nominative; verb agrees with it.",
      english: "The girl sings",
      tokens: ["Puella", "cantat"],
    },
    {
      id: "la-a2-1",
      cefr: "A2",
      pattern: "Accusative object",
      rule: "Direct objects take accusative endings (librum, not liber).",
      english: "I see the girl",
      tokens: ["Puellam", "video"],
    },
    {
      id: "la-a2-2",
      cefr: "A2",
      pattern: "SOV with adjective",
      rule: "Adjectives usually agree with their noun and stay nearby.",
      english: "The good girl reads",
      tokens: ["Puella", "bona", "legit"],
    },
    {
      id: "la-b1-1",
      cefr: "B1",
      pattern: "SOV transitive",
      rule: "Subject → object → verb is a reliable default.",
      english: "The poet writes a letter",
      tokens: ["Poeta", "epistulam", "scribit"],
    },
    {
      id: "la-b1-2",
      cefr: "B1",
      pattern: "Negation non",
      rule: "non usually sits before the verb.",
      english: "I do not love",
      tokens: ["Non", "amo"],
    },
    {
      id: "la-b2-1",
      cefr: "B2",
      pattern: "Prepositional phrase",
      rule: "Preposition + ablative/accusative before or after the core SOV.",
      english: "I walk in the garden",
      tokens: ["In", "horto", "ambulo"],
    },
    {
      id: "la-c1-1",
      cefr: "C1",
      pattern: "Relative clause",
      rule: "qui/quae/quod agrees with its antecedent; verb often still late.",
      english: "the girl who sings",
      tokens: ["puella", "quae", "cantat"],
    },
    {
      id: "la-c2-1",
      cefr: "C2",
      pattern: "Period style",
      rule: "Stack modifiers early; land the main verb at the end.",
      english: "The consul gives the law to the people",
      tokens: ["Consul", "populo", "legem", "dat"],
    },
  ],

  asl: [
    {
      id: "asl-a1-1",
      cefr: "A1",
      pattern: "Topic–comment",
      rule: "Set the topic first, then comment on it.",
      english: "I go to the store",
      tokens: ["STORE", "ME", "GO"],
      note: "Each gloss is one SignASL sign — topic STORE, then ME GO.",
    },
    {
      id: "asl-a1-2",
      cefr: "A1",
      pattern: "Topic–comment",
      rule: "Name the thing, then say what about it.",
      english: "The book is good",
      tokens: ["BOOK", "GOOD"],
    },
    {
      id: "asl-a1-3",
      cefr: "A1",
      pattern: "Time–topic–comment",
      rule: "Time often comes first, then topic, then comment.",
      english: "Tomorrow I go to school",
      tokens: ["TOMORROW", "SCHOOL", "ME", "GO"],
    },
    {
      id: "asl-a2-1",
      cefr: "A2",
      pattern: "Negation",
      rule: "NOT usually follows the verb/comment, with a headshake.",
      english: "I do not want coffee",
      tokens: ["COFFEE", "ME", "WANT", "NOT"],
    },
    {
      id: "asl-a2-2",
      cefr: "A2",
      pattern: "WH-question last",
      rule: "WH signs often come at the end, with furrowed brows.",
      english: "Where is the school?",
      tokens: ["SCHOOL", "WHERE"],
    },
    {
      id: "asl-b1-1",
      cefr: "B1",
      pattern: "Rhetorical question",
      rule: "Ask then answer yourself for emphasis (raised brows).",
      english: "Why? Because I am tired",
      tokens: ["WHY", "ME", "TIRED"],
    },
    {
      id: "asl-b1-2",
      cefr: "B1",
      pattern: "Directional verb",
      rule: "Agreement verbs move from subject locus to object locus.",
      english: "I help you",
      tokens: ["ME", "HELP", "YOU"],
    },
    {
      id: "asl-b2-1",
      cefr: "B2",
      pattern: "Classifier predicate",
      rule: "Name the referent first, then a movement sign.",
      english: "The car drives",
      tokens: ["CAR", "DRIVE"],
    },
    {
      id: "asl-c1-1",
      cefr: "C1",
      pattern: "Role shift",
      rule: "Establish people in space, then shift to quote them.",
      english: "Mother said go home",
      tokens: ["MOTHER", "SAY", "HOME", "GO"],
    },
    {
      id: "asl-c2-1",
      cefr: "C2",
      pattern: "Full TCC narrative",
      rule: "Time → topic → comment keeps longer ASL sentences clear.",
      english: "Yesterday at school I finished homework",
      tokens: ["YESTERDAY", "SCHOOL", "HOMEWORK", "ME", "FINISH"],
    },
  ],

  bsl: [
    {
      id: "bsl-a1-1",
      cefr: "A1",
      pattern: "Topic–comment",
      rule: "BSL often places the topic first, then the comment.",
      english: "I go to the shop",
      tokens: ["SHOP", "I", "GO"],
    },
    {
      id: "bsl-a1-2",
      cefr: "A1",
      pattern: "Topic–comment",
      rule: "Name the topic, then describe it.",
      english: "The book is good",
      tokens: ["BOOK", "GOOD"],
    },
    {
      id: "bsl-a1-3",
      cefr: "A1",
      pattern: "Time first",
      rule: "Time signs commonly lead the sentence.",
      english: "Tomorrow I go to school",
      tokens: ["TOMORROW", "SCHOOL", "I", "GO"],
    },
    {
      id: "bsl-a2-1",
      cefr: "A2",
      pattern: "Negation",
      rule: "Negation often comes with / after the verb and a headshake.",
      english: "I do not want tea",
      tokens: ["TEA", "I", "WANT", "NOT"],
    },
    {
      id: "bsl-a2-2",
      cefr: "A2",
      pattern: "WH last",
      rule: "WH questions frequently end with the WH sign.",
      english: "Where is home?",
      tokens: ["HOME", "WHERE"],
    },
    {
      id: "bsl-b1-1",
      cefr: "B1",
      pattern: "Possessive",
      rule: "Establish the owner, then the possessed thing.",
      english: "My name is…",
      tokens: ["MY", "NAME"],
    },
    {
      id: "bsl-b1-2",
      cefr: "B1",
      pattern: "Two-topic contrast",
      rule: "Set two topics in space, then comment on each.",
      english: "Tea good, coffee bad",
      tokens: ["TEA", "GOOD", "COFFEE", "BAD"],
    },
    {
      id: "bsl-b2-1",
      cefr: "B2",
      pattern: "Role shift",
      rule: "Shift body/gaze to show another person’s line.",
      english: "Teacher said practice",
      tokens: ["TEACHER", "SAY", "PRACTICE"],
    },
    {
      id: "bsl-c1-1",
      cefr: "C1",
      pattern: "Classifier scene",
      rule: "Name entities first, then classifier movement.",
      english: "Person walks to the house",
      tokens: ["HOUSE", "PERSON", "CL:WALK-TO"],
    },
    {
      id: "bsl-c2-1",
      cefr: "C2",
      pattern: "Time–topic–comment",
      rule: "Keep TCC even in longer narratives.",
      english: "Yesterday I finished work at home",
      tokens: ["YESTERDAY", "HOME", "WORK", "I", "FINISH"],
    },
  ],

  isl: [
    {
      id: "isl-a1-1",
      cefr: "A1",
      pattern: "Topic–comment",
      rule: "International Sign contact grammar favors topic then comment.",
      english: "I go to the store",
      tokens: ["STORE", "I", "GO"],
    },
    {
      id: "isl-a1-2",
      cefr: "A1",
      pattern: "Simple comment",
      rule: "Pointing + lexical sign can complete a comment.",
      english: "I am happy",
      tokens: ["I", "HAPPY"],
    },
    {
      id: "isl-a2-1",
      cefr: "A2",
      pattern: "Time first",
      rule: "Put time before the rest of the message.",
      english: "Today I learn",
      tokens: ["TODAY", "I", "LEARN"],
    },
    {
      id: "isl-a2-2",
      cefr: "A2",
      pattern: "WH last",
      rule: "WH signs are often sentence-final in IS.",
      english: "What is your name?",
      tokens: ["YOUR", "NAME", "WHAT"],
    },
    {
      id: "isl-b1-1",
      cefr: "B1",
      pattern: "Negation",
      rule: "NOT / headshake typically follows the denied idea.",
      english: "I do not understand",
      tokens: ["I", "UNDERSTAND", "NOT"],
    },
    {
      id: "isl-b1-2",
      cefr: "B1",
      pattern: "List then comment",
      rule: "Establish referents, then comment on the set.",
      english: "Coffee and tea — I want tea",
      tokens: ["COFFEE", "TEA", "TEA", "I", "WANT"],
    },
    {
      id: "isl-b2-1",
      cefr: "B2",
      pattern: "Role shift",
      rule: "Shift to show another participant’s utterance.",
      english: "Friend said come",
      tokens: ["FRIEND", "SAY", "COME"],
    },
    {
      id: "isl-c1-1",
      cefr: "C1",
      pattern: "Classifier",
      rule: "After naming, classifiers show path/placement.",
      english: "The person goes to school",
      tokens: ["SCHOOL", "PERSON", "GO"],
    },
    {
      id: "isl-c2-1",
      cefr: "C2",
      pattern: "Full TCC",
      rule: "Time → topic → comment keeps IS clear across signers.",
      english: "Tomorrow meeting I finish",
      tokens: ["TOMORROW", "MEETING", "I", "FINISH"],
    },
  ],

  nzsl: [
    {
      id: "nzsl-a1-1",
      cefr: "A1",
      pattern: "Topic–comment",
      rule: "NZSL commonly uses topic first, then comment.",
      english: "I go home",
      tokens: ["HOME", "I", "GO"],
    },
    {
      id: "nzsl-a1-2",
      cefr: "A1",
      pattern: "Topic–comment",
      rule: "Establish the topic, then evaluate it.",
      english: "The food is good",
      tokens: ["FOOD", "GOOD"],
    },
    {
      id: "nzsl-a1-3",
      cefr: "A1",
      pattern: "Time first",
      rule: "Time signs often lead.",
      english: "Tomorrow I go to school",
      tokens: ["TOMORROW", "SCHOOL", "I", "GO"],
    },
    {
      id: "nzsl-a2-1",
      cefr: "A2",
      pattern: "Negation",
      rule: "NOT / NOTHING usually follows with a headshake.",
      english: "I do not want coffee",
      tokens: ["COFFEE", "I", "WANT", "NOT"],
    },
    {
      id: "nzsl-a2-2",
      cefr: "A2",
      pattern: "WH last",
      rule: "WH questions often end with the WH sign.",
      english: "Where is the marae?",
      tokens: ["MARAE", "WHERE"],
    },
    {
      id: "nzsl-b1-1",
      cefr: "B1",
      pattern: "Aotearoa topic",
      rule: "Place/culture topics can lead community talk.",
      english: "In Aotearoa, Māori language is important",
      tokens: ["AOTEAROA", "MĀORI", "LANGUAGE", "IMPORTANT"],
    },
    {
      id: "nzsl-b1-2",
      cefr: "B1",
      pattern: "Possessive",
      rule: "Owner then possessed item.",
      english: "My family",
      tokens: ["MY", "FAMILY"],
    },
    {
      id: "nzsl-b2-1",
      cefr: "B2",
      pattern: "Role shift",
      rule: "Shift to report another person’s signing.",
      english: "Teacher said learn",
      tokens: ["TEACHER", "SAY", "LEARN"],
    },
    {
      id: "nzsl-c1-1",
      cefr: "C1",
      pattern: "Classifier",
      rule: "Name first, then classifier action.",
      english: "The car goes to school",
      tokens: ["SCHOOL", "CAR", "GO"],
    },
    {
      id: "nzsl-c2-1",
      cefr: "C2",
      pattern: "Time–topic–comment",
      rule: "Keep TCC for clear NZSL narratives.",
      english: "Yesterday at home I finished homework",
      tokens: ["YESTERDAY", "HOME", "HOMEWORK", "I", "FINISH"],
    },
  ],
};

export function getGrammarSentences(languageId: LanguageId): GrammarSentence[] {
  return GRAMMAR_SENTENCES[languageId] ?? [];
}

export function getGrammarSentencesByCefr(
  languageId: LanguageId,
  cefr: CefrLevel,
): GrammarSentence[] {
  return getGrammarSentences(languageId).filter((s) => s.cefr === cefr);
}
