import type { UnitId, VocabItem } from "../types";

type Bank = Record<UnitId, VocabItem[]>;

/**
 * International Sign vocab keyed to sonastik.ead.ee word IDs
 * Dictionary: https://sonastik.ead.ee/embed/en/word-list
 * Entry: https://sonastik.ead.ee/embed/en/search?word={sonastik}
 */
function s(
  term: string,
  meaning: string,
  sonastik: string,
  hint?: string,
): VocabItem {
  return { term, meaning, sonastik, hint };
}

export const ISL_VOCAB: Bank = {
  grammar: [
    s("WHAT", "What?", "262", "Interrogative"),
    s("WHO", "Who?", "255"),
    s("WHEN", "When?", "264"),
    s("HOW", "How?", "258"),
    s("WHY", "Why?", "263"),
    s("WHERE", "Where?", "256"),
  ],
  alphabet: [
    s("HELLO", "Hello", "120", "Basic greeting"),
    s("PLEASE", "Please", "133"),
    s("THANK-YOU", "Thank you", "128"),
    s("YES", "Yes", "138"),
    s("NO", "No", "139"),
    s("WELCOME", "Welcome", "124"),
  ],
  pronouns: [
    s("FATHER", "Father", "25"),
    s("FRIEND", "Friend", "96"),
    s("FAMILY", "Family members", "246"),
    s("PERSON", "Person / people", "245"),
    s("STUDENT", "Student", "250"),
    s("TEACHER", "Teacher", "43"),
  ],
  nouns: [
    s("HOME", "Home", "420"),
    s("SCHOOL", "School", "424"),
    s("WATER", "Water", "395"),
    s("FOOD", "Food", "357"),
    s("CULTURE", "Culture", "425"),
    s("COMMUNITY", "Community", "640"),
  ],
  verbs: [
    s("GO", "To go", "832"),
    s("COME", "To come", "862"),
    s("WANT", "To want", "856"),
    s("NEED", "To need", "868"),
    s("LIKE", "To like", "831"),
    s("LEARN", "To learn", "872"),
  ],
  adjectives: [
    s("BIG", "Big", "974"),
    s("SMALL", "Small", "987"),
    s("GOOD", "Good", "932"),
    s("BAD", "Bad", "931"),
    s("FAST", "Fast", "939"),
    s("SLOW", "Slow", "926"),
  ],
  colors: [
    s("GOOD", "Good (practice descriptor)", "932", "Color list is limited in this dictionary"),
    s("BAD", "Bad", "931"),
    s("BIG", "Big", "974"),
    s("SMALL", "Small", "987"),
    s("IMPORTANT", "Important", "658"),
    s("TRADITIONAL", "Traditional", "978"),
  ],
  maths: [
    s("ONE", "One", "1024"),
    s("TWO", "Two", "997"),
    s("THREE", "Three", "1001"),
    s("FIVE", "Five", "1020"),
    s("TEN", "Ten", "1005"),
    s("HUNDRED", "Hundred", "1013"),
  ],
  time: [
    s("NOW", "Now", "1063"),
    s("TOMORROW", "Tomorrow", "1053"),
    s("YESTERDAY", "Yesterday", "1049"),
    s("WEEK", "Week", "1062"),
    s("MONTH", "Month", "1056"),
    s("TIME", "Time", "1046"),
  ],
  emotions: [
    s("HAPPY", "Happy", "970"),
    s("SAD", "Sad", "942"),
    s("LOVE", "I love you", "269"),
    s("STRESS", "Stress", "588"),
    s("IMPORTANT", "Important", "658"),
    s("RESPECT", "Respect", "807"),
  ],
  body: [
    s("EAR", "Ear", "945"),
    s("EYEGLASSES", "Eyeglasses", "201"),
    s("HAT", "Hat", "177"),
    s("SHOES", "Shoes", "168"),
    s("SHIRT", "Shirt", "224"),
    s("COAT", "Coat", "182"),
  ],
  senses: [
    s("SEE-YOU", "See you soon!", "122"),
    s("HEARING-AID", "Hearing aid", "579"),
    s("DEAF", "Deaf", "566"),
    s("READ", "Read", "829"),
    s("THINK", "Think", "806"),
    s("UNDERSTAND", "I understand", "134"),
  ],
  clothing: [
    s("SHIRT", "Shirt", "224"),
    s("SHOES", "Shoes", "168"),
    s("HAT", "Hat", "177"),
    s("COAT", "Coat", "182"),
    s("EYEGLASSES", "Eyeglasses", "201"),
    s("SUNGLASSES", "Sunglasses", "206"),
  ],
  food: [
    s("FOOD", "Food", "357"),
    s("DRINKS", "Drinks", "361"),
    s("BREAD", "Bread", "371"),
    s("MILK", "Milk", "379"),
    s("COFFEE", "Coffee", "367"),
    s("WATER", "Water", "395"),
  ],
  animals: [
    s("DOG", "Dog", "716"),
    s("CAT", "Cat", "714"),
    s("BIRD", "Bird", "721"),
    s("FISH", "Fish", "817"),
    s("COW", "Cow", "718"),
    s("SHEEP", "Sheep", "717"),
  ],
  furniture: [
    s("CHAIR", "Chair", "330"),
    s("TABLE", "Table", "310"),
    s("BED", "Bed", "338"),
    s("DOOR", "Door", "334"),
    s("WINDOW", "Window", "290"),
    s("ARMCHAIR", "Armchair", "333"),
  ],
  occupations: [
    s("TEACHER", "Teacher", "43"),
    s("DOCTOR", "Doctor", "45"),
    s("COOK", "Cook", "85"),
    s("ARTIST", "Artist", "56"),
    s("ACTOR", "Actor", "63"),
    s("POLICEMAN", "Policeman", "70"),
  ],
  school: [
    s("SCHOOL", "School", "424"),
    s("STUDENT", "Student", "250"),
    s("TEACHER", "Teacher", "43"),
    s("LEARN", "To learn", "872"),
    s("READ", "Read", "829"),
    s("EXAMPLE", "Example", "602"),
  ],
  travel: [
    s("WHERE", "Where?", "256"),
    s("AIRPORT", "Airport", "429"),
    s("TRAIN", "Train", "352"),
    s("HOME", "Home", "420"),
    s("RIGHT", "Right", "684"),
    s("HAVE-NICE-TRIP", "Have a nice trip!", "130"),
  ],
  countries: [
    s("CULTURE", "Culture", "425"),
    s("COMMUNITY", "Community", "640"),
    s("GOVERNMENT", "Government", "679"),
    s("LAW", "Law", "668"),
    s("EQUALITY", "Equality", "682"),
    s("AMBASSADOR", "Ambassador", "673"),
  ],
  culture: [
    s("DEAF", "Deaf", "566"),
    s("CULTURE", "Culture", "425"),
    s("COMMUNITY", "Community", "640"),
    s("RESPECT", "Respect", "807"),
    s("TRADITIONAL", "Traditional", "978"),
    s("IMPORTANT", "Important", "658"),
  ],
  medical: [
    s("HOSPITAL", "Hospital", "411"),
    s("PAIN", "Pain", "585"),
    s("MEDICINE", "Medicine", "554"),
    s("HEALTHY", "Healthy", "578"),
    s("EMERGENCY", "Emergency medical treatment", "571"),
    s("DOCTOR", "Doctor", "45"),
  ],
  politics: [
    s("GOVERNMENT", "Government", "679"),
    s("LAW", "Law", "668"),
    s("EQUALITY", "Equality", "682"),
    s("ACCESSIBILITY", "Accessibility", "892"),
    s("ACCEPTANCE", "Acceptance", "543"),
    s("AMBASSADOR", "Ambassador", "673"),
  ],
  technology: [
    s("COMPUTER", "Computer", "753"),
    s("PHONE", "Phone", "770"),
    s("INTERNET", "Internet", "742"),
    s("EMAIL", "E-mail", "734"),
    s("VIDEO", "Video", "805"),
    s("PASSWORD", "Password", "759"),
  ],
  psychology: [
    s("THINK", "Think", "806"),
    s("STRESS", "Stress", "588"),
    s("HAPPY", "Happy", "970"),
    s("SAD", "Sad", "942"),
    s("IMPORTANT", "Important", "658"),
    s("UNDERSTAND", "I understand", "134"),
  ],
  speaking: [
    s("HELLO", "Hello", "120"),
    s("THANK-YOU", "Thank you", "128"),
    s("PLEASE", "Please", "133"),
    s("YES", "Yes", "138"),
    s("NO", "No", "139"),
    s("NICE-TO-MEET-YOU", "Nice to meet you", "123"),
  ],
  reading: [
    s("READ", "Read", "829"),
    s("BOOKSTORE", "Bookstore", "439"),
    s("EXAMPLE", "Example", "602"),
    s("ARTICLE", "Article", "786"),
    s("NEWSLETTER", "Newsletter", "804"),
    s("HISTORY", "History", "595"),
  ],
  writing: [
    s("WRITER", "Writer", "62"),
    s("PEN", "Pen", "188"),
    s("PAPER", "Paper", "186"),
    s("ARTICLE", "Article", "786"),
    s("NEWSLETTER", "Newsletter", "804"),
    s("USERNAME", "Username", "747"),
  ],
  translating: [
    s("EXAMPLE", "Example", "602"),
    s("IMPORTANT", "Important", "658"),
    s("UNDERSTAND", "I understand", "134"),
    s("NOT-UNDERSTAND", "I do not understand", "135"),
    s("LEARN", "To learn", "872"),
    s("THINK", "Think", "806"),
  ],
  slang: [
    s("NOT-AT-ALL", "Not at all / It's okay", "137", "Informal softener"),
    s("EXCUSE-ME", "Excuse me", "136"),
    s("YOU'RE-WELCOME", "You're welcome!", "129"),
    s("SEE-YOU-SOON", "See you soon!", "122"),
    s("I-LOVE-YOU", "I love you", "269"),
    s("HAVE-NICE-TRIP", "Have a nice trip!", "130"),
  ],
  quotes: [
    s("IMPORTANT", "Important", "658"),
    s("RESPECT", "Respect", "807"),
    s("EQUALITY", "Equality", "682"),
    s("COMMUNITY", "Community", "640"),
    s("LEARN", "To learn", "872"),
    s("WELCOME", "Welcome", "124"),
  ],
  media: [
    s("MOVIE", "Movie", "788"),
    s("TELEVISION", "Television", "523"),
    s("MUSIC", "Music", "613"),
    s("ACTOR", "Actor", "63"),
    s("VIDEO", "Video", "805"),
    s("ARTICLE", "Article", "786"),
  ],
};
