import type { UnitId, VocabItem } from "../types";

type Bank = Partial<Record<UnitId, VocabItem[]>>;

/**
 * NZSL vocab keyed to https://www.nzsl.nz/signs/{nzsl}
 * Search: https://www.nzsl.nz/signs/search?s=...
 */
function s(
  term: string,
  meaning: string,
  nzsl: string,
  hint?: string,
): VocabItem {
  return { term, meaning, nzsl, hint };
}

export const NZSL_VOCAB: Bank = {
  grammar: [
    s("NOT", "Not / negation", "3127"),
    s("WHAT", "What", "2266"),
    s("BECAUSE", "Because", "2722"),
    s("FINISH", "Finish / then", "3653"),
    s("HAVE", "Have", "1376"),
    s("QUESTION", "Question", "6010"),
  ],
  alphabet: [
    s("ALPHABET", "Alphabet", "4998"),
    s("NAME", "Name", "2173"),
    s("AOTEAROA", "Aotearoa", "5239"),
    s("MAORI", "Māori", "3204"),
    s("HELLO", "Hello / goodbye", "1301"),
    s("WORD", "Word", "4421"),
  ],
  pronouns: [
    s("I", "I", "2556"),
    s("YOU", "You", "2321"),
    s("HE-SHE-IT", "He / she / it", "2297"),
    s("WE", "We", "2314"),
    s("THEY", "They", "7204"),
    s("FAMILY", "Family / whānau", "1636"),
  ],
  nouns: [
    s("PERSON", "Person", "4446"),
    s("HOME", "Home", "5995"),
    s("SCHOOL", "School", "1298"),
    s("NAME", "Name", "2173"),
    s("WATER", "Water", "1760"),
    s("BOOK", "Book", "523"),
  ],
  verbs: [
    s("GO", "Go", "2582"),
    s("COME", "Come", "2533"),
    s("WANT", "Want", "721"),
    s("NEED", "Need", "1185"),
    s("LIKE", "Like", "8950"),
    s("HELP", "Help", "1123"),
  ],
  adjectives: [
    s("BIG", "Big", "1545"),
    s("SMALL", "Small", "5752"),
    s("GOOD", "Good", "3658"),
    s("BAD", "Bad / wrong", "4581"),
    s("FAST", "Fast", "2256"),
    s("SLOW", "Slow", "6305"),
  ],
  colors: [
    s("RED", "Red", "2174"),
    s("BLUE", "Blue", "478"),
    s("GREEN", "Green", "927"),
    s("YELLOW", "Yellow", "2987"),
    s("BLACK", "Black", "3201"),
    s("WHITE", "White", "3020"),
  ],
  maths: [
    s("ONE", "One", "5607"),
    s("TWO", "Two", "5617"),
    s("THREE", "Three", "5619"),
    s("FIVE", "Five", "5621"),
    s("TEN", "Ten", "8205"),
    s("EQUAL", "Equal / fair", "1040"),
  ],
  time: [
    s("NOW", "Now", "5426"),
    s("TOMORROW", "Tomorrow", "2142"),
    s("YESTERDAY", "Yesterday", "3636"),
    s("WEEK", "Week", "1465"),
    s("MONTH", "Month", "4763"),
    s("TIME", "Time", "5784"),
  ],
  emotions: [
    s("HAPPY", "Happy", "606"),
    s("SAD", "Sad", "332"),
    s("ANGRY", "Angry", "1938"),
    s("SCARED", "Scared of", "5950"),
    s("LOVE", "Love", "8956"),
    s("EXCITED", "Excited", "1864"),
  ],
  body: [
    s("HEAD", "Head", "313"),
    s("EYE", "Eye", "2083"),
    s("HAND", "Hand / hands", "539"),
    s("HEART", "Heart", "8865"),
    s("LEG", "Leg", "2675"),
    s("EAR", "Ear", "5741"),
  ],
  senses: [
    s("SEE", "See", "2091"),
    s("HEAR", "Hear / listen", "335"),
    s("TOUCH", "Touch", "1164"),
    s("SMELL", "Smell", "2102"),
    s("TASTE", "Taste / flavour", "2226"),
    s("FEEL", "Feel", "5536"),
  ],
  clothing: [
    s("SHIRT", "Shirt", "4360"),
    s("PANTS", "Pants", "6111"),
    s("SHOES", "Shoe", "4307"),
    s("HAT", "Hat", "4970"),
    s("COAT", "Coat", "3844"),
    s("GLASSES", "Glasses", "4191"),
  ],
  food: [
    s("EAT", "Eat / food", "4022"),
    s("DRINK", "Drink", "4264"),
    s("BREAD", "Bread", "780"),
    s("MILK", "Milk", "5659"),
    s("FRUIT", "Fruit", "4199"),
    s("COFFEE", "Coffee", "7080"),
  ],
  animals: [
    s("DOG", "Dog", "1124"),
    s("CAT", "Cat", "4503"),
    s("BIRD", "Bird / chicken", "4508"),
    s("FISH", "Fish", "751"),
    s("HORSE", "Horse", "3382"),
    s("COW", "Cow", "4008"),
  ],
  furniture: [
    s("CHAIR", "Chair / sit", "1085"),
    s("TABLE", "Table", "834"),
    s("BED", "Bed", "3192"),
    s("DOOR", "Door", "570"),
    s("WINDOW", "Window", "6308"),
    s("LAMP", "Lamp", "4005"),
  ],
  occupations: [
    s("TEACHER", "Teacher", "2021"),
    s("DOCTOR", "Doctor", "4520"),
    s("NURSE", "Nurse", "4423"),
    s("POLICE", "Police", "2943"),
    s("COOK", "Cook", "3875"),
    s("PAINT", "Paint / artist-related", "1274"),
  ],
  school: [
    s("STUDENT", "Student", "3409"),
    s("CLASS", "Class", "4249"),
    s("HOMEWORK", "Homework", "5814"),
    s("TEST", "Test", "3898"),
    s("QUESTION", "Question", "6010"),
    s("ANSWER", "Answer", "2617"),
  ],
  travel: [
    s("WHERE", "Where", "1544"),
    s("HERE", "Here", "2579"),
    s("LEFT", "Left", "815"),
    s("RIGHT", "Right", "6252"),
    s("PLANE", "Airport / plane", "4731"),
    s("TRAIN", "Train", "5934"),
  ],
  countries: [
    s("NEW-ZEALAND", "New Zealand", "585"),
    s("AOTEAROA", "Aotearoa", "5239"),
    s("AUSTRALIA", "Australia", "4939"),
    s("ENGLAND", "England / English", "2456"),
    s("SAMOA", "Samoa", "5946"),
    s("FIJI", "Fiji", "6091"),
  ],
  culture: [
    s("DEAF", "Deaf", "4656"),
    s("HEARING", "Hearing", "2117"),
    s("CULTURE", "Culture", "1765"),
    s("COMMUNITY", "Community", "567"),
    s("RESPECT", "Respect", "468"),
    s("MARAE", "Marae", "5919"),
  ],
  medical: [
    s("HOSPITAL", "Hospital", "1806"),
    s("PAIN", "Injury / suffer", "1561"),
    s("MEDICINE", "Medicine (liquid)", "4202"),
    s("SICK", "Sick", "3213"),
    s("HEALTH", "Health", "1603"),
    s("EMERGENCY", "Emergency", "5419"),
  ],
  politics: [
    s("VOTE", "Vote", "5989"),
    s("LAW", "Law", "4859"),
    s("GOVERNMENT", "Government", "1772"),
    s("EQUAL", "Equal / fair", "1040"),
    s("PEACEFUL", "Peaceful", "2920"),
    s("IMPORTANT", "Important", "5509"),
  ],
  technology: [
    s("COMPUTER", "Computer", "1659"),
    s("PHONE", "Phone", "4736"),
    s("INTERNET", "Internet", "5510"),
    s("EMAIL", "Email", "5348"),
    s("VIDEO", "Video", "2897"),
    s("WORD", "Word", "4421"),
  ],
  psychology: [
    s("THINK", "Think", "2050"),
    s("REMEMBER", "Remember / memory", "4189"),
    s("FORGET", "Forget", "1319"),
    s("STRESS", "Stress", "5449"),
    s("CALM", "Calm", "712"),
    s("FEEL", "Feel", "5536"),
  ],
  speaking: [
    s("HELLO", "Hello / goodbye", "1301"),
    s("THANK", "Thank / thank you", "1015"),
    s("PLEASE", "Please", "8974"),
    s("SORRY", "Sorry", "1708"),
    s("YES", "Yes", "3236"),
    s("NO", "No", "1464"),
  ],
  reading: [
    s("READ", "Read", "2895"),
    s("STORY", "Story", "1038"),
    s("SENTENCE", "Sentence", "2497"),
    s("WORD", "Word", "4421"),
    s("TITLE", "Title", "5775"),
    s("BOOK", "Book", "523"),
  ],
  writing: [
    s("WRITE", "Write", "3867"),
    s("LETTER", "Letter", "5481"),
    s("LIST", "Long list", "1033"),
    s("NOTE", "Note", "5521"),
    s("PAPER", "Paper", "3301"),
    s("PEN", "Pen", "5998"),
  ],
  translating: [
    s("INTERPRET", "Interpret / interpreter", "3063"),
    s("MEANING", "Meaning", "4835"),
    s("SAME", "Same", "2961"),
    s("DIFFERENT", "Different", "8936"),
    s("EXAMPLE", "For example", "2473"),
    s("COMPARE", "Compare", "1055"),
  ],
  slang: [
    s("YUCK", "Yuck", "405", "Informal dislike"),
    s("REALLY", "Really", "579", "Informal emphasis"),
    s("WHOOPS", "Whoops", "5109", "Informal"),
    s("EXCUSE-ME", "Excuse me", "2455"),
    s("DAMN", "Damn", "3237", "Mild swear — careful"),
    s("SWEAR", "Swear", "2187", "Use carefully"),
  ],
  quotes: [
    s("IMPORTANT", "Important", "5509"),
    s("RESPECT", "Respect", "468"),
    s("PRACTICE", "Practice", "3310"),
    s("LEARN", "Learn", "1513"),
    s("TOGETHER", "Get together", "1876"),
    s("EQUAL", "Equal / fair", "1040"),
  ],
  media: [
    s("MOVIE", "Movie", "1421"),
    s("TELEVISION", "Television", "2382"),
    s("BOOK", "Book", "523"),
    s("DRAMA", "Drama / acting", "5455"),
    s("MUSIC", "Music", "2516"),
    s("SUBTITLES", "Subtitles", "4400"),
  ],
};
