import { UNIT_CEFR } from "../cefr";
import type { CefrLevel, LanguageId, UnitId, VocabItem } from "../types";
import { ASL_VOCAB } from "./asl";
import { BSL_VOCAB } from "./bsl";
import { EXTRA_VOCAB } from "./extra-units";
import { ISL_VOCAB } from "./isl";
import { NZSL_VOCAB } from "./nzsl";
import { TIER_BANKS } from "./tiers";

type Bank = Partial<Record<UnitId, VocabItem[]>>;

const signedShared = {
  grammar: [
    { term: "Topic-comment", meaning: "State the topic first, then comment", hint: "Core signed word order pattern" },
    { term: "Non-manual markers", meaning: "Facial expression and head movement that carry grammar", hint: "Eyebrows, mouth, head tilt" },
    { term: "Classifier", meaning: "Handshape that represents a class of objects", hint: "CL:3 for vehicles in many SLs" },
    { term: "Role shift", meaning: "Take on another person's viewpoint in space", hint: "Shoulder/eye gaze shift" },
    { term: "Rhetorical question", meaning: "Ask then answer yourself for emphasis", hint: "Raised brows, then answer" },
    { term: "Negation", meaning: "Deny with headshake + negative sign", hint: "Often NOT + headshake" },
  ],
  alphabet: [
    { term: "Fingerspelling", meaning: "Spell words letter by letter with the hand", hint: "Names, places, loanwords" },
    { term: "A", meaning: "Closed fist with thumb alongside", hint: "First letter" },
    { term: "B", meaning: "Flat hand, fingers together, thumb across palm", hint: "Second letter" },
    { term: "C", meaning: "Curved hand like the letter C", hint: "Third letter" },
    { term: "Initialization", meaning: "Sign that starts with a fingerspelled letter", hint: "Common in ASL" },
    { term: "Lexicalized fingerspelling", meaning: "Fingerspelled word that became a sign", hint: "e.g. #JOB, #BUS" },
  ],
  pronouns: [
    { term: "I / ME", meaning: "Point to yourself", hint: "Index to chest" },
    { term: "YOU", meaning: "Point to the person", hint: "Index forward" },
    { term: "HE / SHE / THEY", meaning: "Point to established space", hint: "Index to locus" },
    { term: "WE", meaning: "Sweep including self and others", hint: "Inclusive arc" },
    { term: "POSSESSIVE", meaning: "Flat hand toward owner", hint: "MY, YOUR, THEIR" },
    { term: "REFLEXIVE", meaning: "SELF / MYSELF forms", hint: "A-hand to chest" },
  ],
  nouns: [
    { term: "PERSON", meaning: "Human being", hint: "Agent marker often added" },
    { term: "HOME", meaning: "Place where you live", hint: "Flat-O to cheek twice (ASL-like)" },
    { term: "SCHOOL", meaning: "Place of learning", hint: "Clapping flat hands" },
    { term: "NAME", meaning: "What someone is called", hint: "H-hands tap" },
    { term: "WATER", meaning: "H2O / drinkable liquid", hint: "W at chin" },
    { term: "BOOK", meaning: "Bound pages for reading", hint: "Open palms like opening a book" },
  ],
  verbs: [
    { term: "GO", meaning: "Move toward a place", hint: "Directional path" },
    { term: "COME", meaning: "Move toward signer", hint: "Path toward body" },
    { term: "WANT", meaning: "Desire something", hint: "Claw hands pull in" },
    { term: "NEED", meaning: "Require something", hint: "X-hand downward" },
    { term: "LIKE", meaning: "Enjoy / prefer", hint: "Middle finger from chest" },
    { term: "HELP", meaning: "Assist someone", hint: "A on flat palm, lift" },
  ],
  adjectives: [
    { term: "BIG", meaning: "Large in size", hint: "Hands expand" },
    { term: "SMALL", meaning: "Little in size", hint: "Fingers pinch / close" },
    { term: "GOOD", meaning: "Positive quality", hint: "Flat hand from chin" },
    { term: "BAD", meaning: "Negative quality", hint: "Flat hand flips from chin" },
    { term: "FAST", meaning: "Quick", hint: "Quick snap movement" },
    { term: "SLOW", meaning: "Not fast", hint: "Slow drag across hand" },
  ],
  colors: [
    { term: "RED", meaning: "Color of blood / stop lights", hint: "Index brush lip" },
    { term: "BLUE", meaning: "Color of clear sky", hint: "Shake B-hand" },
    { term: "GREEN", meaning: "Color of grass", hint: "Shake G-hand" },
    { term: "YELLOW", meaning: "Color of the sun / bananas", hint: "Shake Y-hand" },
    { term: "BLACK", meaning: "Darkest color", hint: "Index across forehead" },
    { term: "WHITE", meaning: "Color of snow / paper", hint: "Open hand from chest out" },
  ],
  maths: [
    { term: "ONE", meaning: "Number 1", hint: "Index up" },
    { term: "TWO", meaning: "Number 2", hint: "Index + middle" },
    { term: "FIVE", meaning: "Number 5", hint: "Open hand" },
    { term: "TEN", meaning: "Number 10", hint: "A-hand shake / thumb up variants" },
    { term: "PLUS", meaning: "Addition", hint: "Cross index fingers" },
    { term: "MINUS", meaning: "Subtraction", hint: "Sideways index swipe" },
  ],
  time: [
    { term: "NOW", meaning: "At this moment", hint: "Y-hands drop" },
    { term: "TOMORROW", meaning: "The next day", hint: "A-hand forward from cheek" },
    { term: "YESTERDAY", meaning: "The previous day", hint: "A-hand back from cheek" },
    { term: "WEEK", meaning: "Seven days", hint: "1 across palm" },
    { term: "MONTH", meaning: "About 30 days", hint: "1 down palm" },
    { term: "TIME", meaning: "Clock / when", hint: "Tap wrist" },
  ],
  emotions: [
    { term: "HAPPY", meaning: "Feeling joy", hint: "Brush chest upward" },
    { term: "SAD", meaning: "Feeling down", hint: "Fingers down face" },
    { term: "ANGRY", meaning: "Feeling mad", hint: "Claw up chest / face" },
    { term: "SCARED", meaning: "Feeling fear", hint: "S-hands open at chest" },
    { term: "LOVE", meaning: "Deep affection", hint: "Cross arms on chest" },
    { term: "EXCITED", meaning: "Eager energy", hint: "Middle fingers alt on chest" },
  ],
  body: [
    { term: "HEAD", meaning: "Top of body", hint: "Tap temple" },
    { term: "EYE", meaning: "Organ of sight", hint: "Point under eye" },
    { term: "HAND", meaning: "End of arm", hint: "Show / tap hand" },
    { term: "HEART", meaning: "Chest organ / love center", hint: "Middle finger to chest" },
    { term: "LEG", meaning: "Lower limb", hint: "Pat thigh" },
    { term: "EAR", meaning: "Organ of hearing", hint: "Point to ear" },
  ],
  senses: [
    { term: "SEE", meaning: "Perceive with eyes", hint: "V from eyes out" },
    { term: "HEAR", meaning: "Perceive sound", hint: "Index to ear" },
    { term: "TOUCH", meaning: "Feel with hands", hint: "Middle finger tap back of hand" },
    { term: "SMELL", meaning: "Perceive odor", hint: "Hand at nose" },
    { term: "TASTE", meaning: "Perceive flavor", hint: "Middle finger to chin" },
    { term: "FEEL", meaning: "Emotion or tactile sense", hint: "Middle finger up chest" },
  ],
  clothing: [
    { term: "SHIRT", meaning: "Upper garment", hint: "Pinch at chest" },
    { term: "PANTS", meaning: "Lower garment", hint: "Hands down hips" },
    { term: "SHOES", meaning: "Footwear", hint: "Fists tap" },
    { term: "HAT", meaning: "Head covering", hint: "Pat head" },
    { term: "COAT", meaning: "Outerwear", hint: "A-hands down torso" },
    { term: "GLASSES", meaning: "Eyewear", hint: "G near eyes" },
  ],
  food: [
    { term: "EAT", meaning: "Consume food", hint: "Flat-O to mouth" },
    { term: "DRINK", meaning: "Consume liquid", hint: "C to mouth" },
    { term: "BREAD", meaning: "Baked staple", hint: "Knife on hand" },
    { term: "MILK", meaning: "Dairy drink", hint: "Milking motion" },
    { term: "APPLE", meaning: "Fruit", hint: "X twist at cheek" },
    { term: "COFFEE", meaning: "Caffeinated drink", hint: "Fist grind on fist" },
  ],
  animals: [
    { term: "DOG", meaning: "Canine pet", hint: "Snap / pat thigh" },
    { term: "CAT", meaning: "Feline pet", hint: "Whiskers from cheek" },
    { term: "BIRD", meaning: "Flying animal", hint: "Beak at mouth" },
    { term: "FISH", meaning: "Aquatic animal", hint: "Wiggle hand forward" },
    { term: "HORSE", meaning: "Large riding animal", hint: "Hears at head" },
    { term: "COW", meaning: "Bovine farm animal", hint: "Y at temples" },
  ],
  furniture: [
    { term: "CHAIR", meaning: "Seat", hint: "H on H sit" },
    { term: "TABLE", meaning: "Flat surface for work/meals", hint: "Forearms together" },
    { term: "BED", meaning: "Place to sleep", hint: "Palm to cheek + rest" },
    { term: "DOOR", meaning: "Entryway", hint: "Door swing" },
    { term: "WINDOW", meaning: "Glass opening", hint: "Open/close mid-air" },
    { term: "LAMP", meaning: "Light source", hint: "Open hand flash" },
  ],
  occupations: [
    { term: "TEACHER", meaning: "Educates students", hint: "TEACH + PERSON" },
    { term: "DOCTOR", meaning: "Medical professional", hint: "M on pulse / cross" },
    { term: "NURSE", meaning: "Healthcare caregiver", hint: "N on pulse" },
    { term: "POLICE", meaning: "Law enforcement", hint: "C on badge area" },
    { term: "CHEF", meaning: "Cooks food", hint: "COOK + PERSON" },
    { term: "ARTIST", meaning: "Creates art", hint: "Paint on palm + PERSON" },
  ],
  school: [
    { term: "STUDENT", meaning: "Learner", hint: "LEARN + PERSON" },
    { term: "CLASS", meaning: "Group of learners", hint: "C-hands circle" },
    { term: "HOMEWORK", meaning: "Work done at home", hint: "HOME + WORK" },
    { term: "TEST", meaning: "Assessment", hint: "X fingers draw check" },
    { term: "QUESTION", meaning: "Inquiry", hint: "Index draw ?" },
    { term: "ANSWER", meaning: "Response", hint: "Index from mouth forward" },
  ],
  travel: [
    { term: "WHERE", meaning: "Ask location", hint: "Shake index" },
    { term: "HERE", meaning: "This place", hint: "Palms circle down" },
    { term: "LEFT", meaning: "Direction left", hint: "L hand left" },
    { term: "RIGHT", meaning: "Direction right", hint: "R hand right" },
    { term: "AIRPLANE", meaning: "Flying vehicle", hint: "ILY hand soar" },
    { term: "TRAIN", meaning: "Rail transport", hint: "U on U rub" },
  ],
  countries: [
    { term: "AMERICA", meaning: "United States (region sense)", hint: "Interlocked circles" },
    { term: "ENGLAND", meaning: "Country in UK", hint: "Tea-pour / variants" },
    { term: "CHINA", meaning: "East Asian country", hint: "Index at chest / M variants" },
    { term: "SPAIN", meaning: "European country", hint: "X at shoulders" },
    { term: "NETHERLANDS", meaning: "Holland / NL", hint: "Y windmill motion" },
    { term: "NEW ZEALAND", meaning: "Aotearoa", hint: "N-Z / island variants" },
  ],
  culture: [
    { term: "DEAF", meaning: "Deaf identity / community", hint: "Index ear to mouth" },
    { term: "HEARING", meaning: "Hearing person", hint: "Finger circle at mouth" },
    { term: "CULTURE", meaning: "Shared ways of life", hint: "C circles palm" },
    { term: "COMMUNITY", meaning: "Group of people", hint: "C hands together" },
    { term: "TRADITION", meaning: "Passed-down practice", hint: "A hands pass back" },
    { term: "RESPECT", meaning: "Honor someone", hint: "R forward from forehead" },
  ],
  medical: [
    { term: "HOSPITAL", meaning: "Medical facility", hint: "H cross on shoulder" },
    { term: "PAIN", meaning: "Hurt / ache", hint: "Index jab mid-air" },
    { term: "MEDICINE", meaning: "Treatment substance", hint: "Middle finger grind palm" },
    { term: "SICK", meaning: "Ill", hint: "Middle to forehead + stomach" },
    { term: "HEALTHY", meaning: "In good health", hint: "H hands down body" },
    { term: "EMERGENCY", meaning: "Urgent crisis", hint: "E shake" },
  ],
  politics: [
    { term: "VOTE", meaning: "Cast a ballot", hint: "V into O" },
    { term: "LAW", meaning: "Legal rule", hint: "L down palm" },
    { term: "GOVERNMENT", meaning: "Ruling body", hint: "G at temple circle" },
    { term: "RIGHTS", meaning: "Entitlements", hint: "R down palm" },
    { term: "PEACE", meaning: "Absence of conflict", hint: "Hands clasp then open" },
    { term: "EQUAL", meaning: "Same status", hint: "Flat hands tap" },
  ],
  technology: [
    { term: "COMPUTER", meaning: "Computing device", hint: "C at forehead / typing" },
    { term: "PHONE", meaning: "Telephone", hint: "Y at ear and mouth" },
    { term: "INTERNET", meaning: "Global network", hint: "Middle fingers tap" },
    { term: "EMAIL", meaning: "Electronic mail", hint: "E to palm / #EMAIL" },
    { term: "VIDEO", meaning: "Moving image", hint: "V shake at eye" },
    { term: "PASSWORD", meaning: "Secret access code", hint: "Fingerspell / lock mime" },
  ],
  psychology: [
    { term: "MIND", meaning: "Thought / cognition", hint: "Index at temple" },
    { term: "THINK", meaning: "Use the mind", hint: "Index circle at temple" },
    { term: "REMEMBER", meaning: "Keep in memory", hint: "A from forehead to hand" },
    { term: "FORGET", meaning: "Lose from memory", hint: "Open hand wipe forehead" },
    { term: "STRESS", meaning: "Mental pressure", hint: "Claw press down" },
    { term: "CALM", meaning: "Peaceful state", hint: "Hands settle down" },
  ],
  speaking: [
    { term: "HELLO", meaning: "Greeting", hint: "Salute from forehead" },
    { term: "THANK YOU", meaning: "Express gratitude", hint: "Flat hand from chin" },
    { term: "PLEASE", meaning: "Polite request", hint: "Flat hand circle chest" },
    { term: "SORRY", meaning: "Apology", hint: "A circle on chest" },
    { term: "YES", meaning: "Affirmative", hint: "S nod" },
    { term: "NO", meaning: "Negative", hint: "Index-middle close to thumb" },
  ],
  reading: [
    { term: "READ", meaning: "Look at and understand text", hint: "V scan palm" },
    { term: "STORY", meaning: "Narrative", hint: "Open hands forward alt" },
    { term: "SENTENCE", meaning: "Grammatical unit", hint: "F hands pull apart" },
    { term: "WORD", meaning: "Lexical item", hint: "G tap on palm" },
    { term: "TITLE", meaning: "Name of a work", hint: "T / Fingerspell" },
    { term: "CAPTION", meaning: "On-screen text", hint: "Quotes + text mime" },
  ],
  writing: [
    { term: "WRITE", meaning: "Form letters on a surface", hint: "Mime pen on palm" },
    { term: "LETTER", meaning: "Written message / alphabet unit", hint: "A to palm / fingerspell" },
    { term: "LIST", meaning: "Ordered items", hint: "Fingers down palm" },
    { term: "NOTE", meaning: "Short written record", hint: "Write then fold" },
    { term: "SIGN NAME", meaning: "Personal name sign", hint: "Unique personal sign" },
    { term: "GLOSS", meaning: "English label for a sign", hint: "Written in CAPS" },
  ],
  translating: [
    { term: "INTERPRET", meaning: "Relay meaning between languages", hint: "F hands flip" },
    { term: "MEANING", meaning: "Sense of a word/sign", hint: "F mid-air twist" },
    { term: "SAME", meaning: "Equivalent", hint: "Y side to side" },
    { term: "DIFFERENT", meaning: "Not the same", hint: "Index cross apart" },
    { term: "EXAMPLE", meaning: "Illustration", hint: "Index from palm out" },
    { term: "COMPARE", meaning: "Contrast two things", hint: "Palms rock" },
  ],
  slang: [
    { term: "WHATEVER", meaning: "Dismissive 'I don't care'", hint: "Y-hands flick (informal)", note: "Casual; can feel rude" },
    { term: "COOL", meaning: "Awesome / alright", hint: "Thumb-up variants / C at chest", note: "Positive informal" },
    { term: "GROSS", meaning: "Disgusting", hint: "Claw down chest + face", note: "Strong dislike" },
    { term: "DUMB", meaning: "Unwise (insulting)", hint: "A at forehead", note: "Avoid — insulting" },
    { term: "SHUT UP", meaning: "Stop talking (rude)", hint: "Zip lips mime", note: "Rude; use carefully" },
    { term: "OH I SEE", meaning: "Understanding / 'ahh'", hint: "Y chin flick", note: "Very common ASL slang-ish" },
  ],
  quotes: [
    { term: "Practice makes progress", meaning: "Repetition improves skill", hint: "Common learner saying" },
    { term: "Deaf gain", meaning: "Value of Deaf ways of being", hint: "Cultural concept" },
    { term: "Eyes are ears", meaning: "Vision carries language for signers", hint: "Community saying" },
    { term: "Nothing about us without us", meaning: "Include the community in decisions", hint: "Advocacy motto" },
    { term: "Sign with your face", meaning: "Non-manuals matter", hint: "Teacher tip" },
    { term: "Space is grammar", meaning: "Location carries meaning", hint: "Spatial linguistics" },
  ],
  media: [
    { term: "MOVIE", meaning: "Film", hint: "5-hand shake at chin/palm" },
    { term: "TV", meaning: "Television", hint: "T+V / box mime" },
    { term: "BOOK", meaning: "Bound reading work", hint: "Open palms" },
    { term: "ACTOR", meaning: "Performer", hint: "A circles face + PERSON" },
    { term: "MUSIC", meaning: "Song / melody", hint: "Swing over arm" },
    { term: "SUBTITLES", meaning: "Text under video", hint: "Quotes under screen" },
  ],
} satisfies Bank;

function aslBank(): Bank {
  return ASL_VOCAB;
}

function bslBank(): Bank {
  return BSL_VOCAB;
}

function islBank(): Bank {
  return ISL_VOCAB;
}

function nzslBank(): Bank {
  return NZSL_VOCAB;
}

const maori: Bank = {
  grammar: [
    { term: "VSO tendency", meaning: "Verb often comes before the subject", hint: "Kei te kai au" },
    { term: "te / ngā", meaning: "the (singular / plural)", hint: "Articles" },
    { term: "he", meaning: "a / some", hint: "Indefinite" },
    { term: "kei te", meaning: "present continuous marker", hint: "Kei te haere" },
    { term: "i", meaning: "past tense marker", hint: "I kai au" },
    { term: "ka", meaning: "future / narrative marker", hint: "Ka haere au" },
  ],
  alphabet: [
    { term: "a e i o u", meaning: "Five vowel sounds", hint: "Pure vowels", romanization: "a e i o u" },
    { term: "wh", meaning: "Like English f (often)", hint: "whānau", romanization: "f-sound" },
    { term: "ng", meaning: "Like singer ng", hint: "ngā", romanization: "ng" },
    { term: "r", meaning: "Flapped r", hint: "Aroha", romanization: "r" },
    { term: "macron (tohutō)", meaning: "Lengthens a vowel", hint: "Māori vs Maori", romanization: "ā ē ī ō ū" },
    { term: "10 consonants", meaning: "h k m n p r t w ng wh", hint: "Compact alphabet" },
  ],
  pronouns: [
    { term: "au / ahau", meaning: "I / me", romanization: "ow / a-how" },
    { term: "koe", meaning: "you (singular)", romanization: "ko-eh" },
    { term: "ia", meaning: "he / she / they (singular)", romanization: "ee-ah" },
    { term: "tāua", meaning: "we two (you and I)", romanization: "taa-oo-ah", hint: "Inclusive dual" },
    { term: "māua", meaning: "we two (not you)", romanization: "maa-oo-ah", hint: "Exclusive dual" },
    { term: "rātou", meaning: "they (plural)", romanization: "raa-tow" },
  ],
  nouns: [
    { term: "whare", meaning: "house", romanization: "fa-reh" },
    { term: "wai", meaning: "water", romanization: "why" },
    { term: "tangata", meaning: "person / people", romanization: "tang-ah-tah" },
    { term: "ingoa", meaning: "name", romanization: "ee-ngo-ah" },
    { term: "whenua", meaning: "land", romanization: "fe-noo-ah" },
    { term: "moana", meaning: "sea / ocean", romanization: "mo-ah-nah" },
  ],
  verbs: [
    { term: "haere", meaning: "go / come", romanization: "high-reh" },
    { term: "kai", meaning: "eat / food", romanization: "kye" },
    { term: "inu", meaning: "drink", romanization: "ee-noo" },
    { term: "titiro", meaning: "look", romanization: "tee-tee-ro" },
    { term: "whakarongo", meaning: "listen", romanization: "fa-ka-rongo" },
    { term: "kōrero", meaning: "speak / talk", romanization: "koo-reh-ro" },
  ],
  adjectives: [
    { term: "pai", meaning: "good", romanization: "pie" },
    { term: "kino", meaning: "bad", romanization: "kee-no" },
    { term: "nui", meaning: "big / many", romanization: "noo-ee" },
    { term: "iti", meaning: "small", romanization: "ee-tee" },
    { term: "hou", meaning: "new", romanization: "ho" },
    { term: "tawhito", meaning: "old", romanization: "ta-fee-to" },
  ],
  colors: [
    { term: "whero", meaning: "red", romanization: "fe-ro" },
    { term: "kākāriki", meaning: "green", romanization: "kaa-kaa-ree-kee" },
    { term: "kōwhai", meaning: "yellow", romanization: "koo-fye" },
    { term: "pango", meaning: "black", romanization: "pang-o" },
    { term: "mā", meaning: "white", romanization: "maa" },
    { term: "kikorangi", meaning: "blue", romanization: "kee-ko-rangi" },
  ],
  maths: [
    { term: "tahi", meaning: "one", romanization: "ta-hee" },
    { term: "rua", meaning: "two", romanization: "roo-ah" },
    { term: "toru", meaning: "three", romanization: "to-roo" },
    { term: "whā", meaning: "four", romanization: "faa" },
    { term: "rima", meaning: "five", romanization: "ree-mah" },
    { term: "tekau", meaning: "ten", romanization: "teh-kow" },
  ],
  time: [
    { term: "āianei", meaning: "now", romanization: "eye-ah-nay" },
    { term: "āpōpō", meaning: "tomorrow", romanization: "aah-paw-paw" },
    { term: "inanahi", meaning: "yesterday", romanization: "ee-na-na-hee" },
    { term: "rā", meaning: "day / sun", romanization: "raa" },
    { term: "wiki", meaning: "week", romanization: "wee-kee" },
    { term: "marama", meaning: "month / moon", romanization: "ma-ra-ma" },
  ],
  emotions: [
    { term: "harikoa", meaning: "happy", romanization: "ha-ree-ko-ah" },
    { term: "pōuri", meaning: "sad", romanization: "paw-oo-ree" },
    { term: "riri", meaning: "angry", romanization: "ree-ree" },
    { term: "mataku", meaning: "afraid", romanization: "ma-ta-koo" },
    { term: "aroha", meaning: "love / compassion", romanization: "ah-ro-ha" },
    { term: "pāroa", meaning: "lonely / longing", romanization: "paa-ro-ah" },
  ],
  body: [
    { term: "upoko", meaning: "head", romanization: "oo-po-ko" },
    { term: "kanohi", meaning: "face / eye", romanization: "ka-no-hee" },
    { term: "ringa", meaning: "hand / arm", romanization: "ring-ah" },
    { term: "waewae", meaning: "leg / foot", romanization: "wye-wye" },
    { term: "ngākau", meaning: "heart / feelings", romanization: "ngaah-kow" },
    { term: "taringa", meaning: "ear", romanization: "ta-ring-ah" },
  ],
  senses: [
    { term: "kite", meaning: "see / find", romanization: "kee-teh" },
    { term: "rongo", meaning: "hear / feel / smell / taste", romanization: "rongo", hint: "Broad sensory verb" },
    { term: "pa", meaning: "touch / contact", romanization: "pah" },
    { term: "hongi", meaning: "smell / press noses", romanization: "hong-ee" },
    { term: "tāmata", meaning: "taste / try", romanization: "taa-ma-ta" },
    { term: "whāwhā", meaning: "feel by touch", romanization: "faa-faa" },
  ],
  clothing: [
    { term: "kākahu", meaning: "clothes", romanization: "kaa-ka-hoo" },
    { term: "hū", meaning: "shoes", romanization: "hoo" },
    { term: "pōtae", meaning: "hat", romanization: "paw-tye" },
    { term: "hāte", meaning: "shirt", romanization: "haa-teh" },
    { term: "tarau", meaning: "trousers", romanization: "ta-row" },
    { term: "koti", meaning: "coat / jacket", romanization: "ko-tee" },
  ],
  food: [
    { term: "kai", meaning: "food / eat", romanization: "kye" },
    { term: "wai", meaning: "water", romanization: "why" },
    { term: "miraka", meaning: "milk", romanization: "mee-ra-ka" },
    { term: "parāoa", meaning: "bread / flour", romanization: "pa-raa-o-ah" },
    { term: "ika", meaning: "fish", romanization: "ee-ka" },
    { term: "hua rākau", meaning: "fruit", romanization: "hoo-ah raa-kow" },
  ],
  animals: [
    { term: "kurī", meaning: "dog", romanization: "koo-ree" },
    { term: "ngeru", meaning: "cat", romanization: "nge-roo" },
    { term: "manu", meaning: "bird", romanization: "ma-noo" },
    { term: "ika", meaning: "fish", romanization: "ee-ka" },
    { term: "hōiho", meaning: "horse", romanization: "hoy-ho" },
    { term: "kiwi", meaning: "kiwi bird", romanization: "kee-wee" },
  ],
  furniture: [
    { term: "tūru", meaning: "chair", romanization: "too-roo" },
    { term: "tēpu", meaning: "table", romanization: "teh-poo" },
    { term: "moenga", meaning: "bed", romanization: "mo-eng-ah" },
    { term: "kūaha", meaning: "door", romanization: "koo-ah-ha" },
    { term: "matapihi", meaning: "window", romanization: "ma-ta-pee-hee" },
    { term: "rama", meaning: "lamp / light", romanization: "ra-ma" },
  ],
  occupations: [
    { term: "kaiako", meaning: "teacher", romanization: "kye-ah-ko" },
    { term: "tākuta", meaning: "doctor", romanization: "taa-koo-ta" },
    { term: "nehi", meaning: "nurse", romanization: "neh-hee" },
    { term: "pirihimana", meaning: "police officer", romanization: "pee-ree-hee-ma-na" },
    { term: "kuki", meaning: "cook", romanization: "koo-kee" },
    { term: "kaitito", meaning: "composer / writer", romanization: "kye-tee-to" },
  ],
  school: [
    { term: "kura", meaning: "school", romanization: "koo-rah" },
    { term: "ākonga", meaning: "student / learner", romanization: "aah-kong-ah" },
    { term: "mahi kāinga", meaning: "homework", romanization: "ma-hee kaa-ee-nga" },
    { term: "pātai", meaning: "question", romanization: "paa-tye" },
    { term: "whakautu", meaning: "answer", romanization: "fa-kow-too" },
    { term: "ako", meaning: "learn / teach", romanization: "ah-ko" },
  ],
  travel: [
    { term: "keihā", meaning: "where?", romanization: "kay-haa" },
    { term: "konei", meaning: "here", romanization: "ko-nay" },
    { term: "maui", meaning: "left", romanization: "mow-ee" },
    { term: "matau", meaning: "right", romanization: "ma-tow" },
    { term: "waka rererangi", meaning: "airplane", romanization: "wa-ka reh-reh-rangi" },
    { term: "tereina", meaning: "train", romanization: "teh-ray-na" },
  ],
  countries: [
    { term: "Aotearoa", meaning: "New Zealand", romanization: "ow-teh-ah-ro-ah" },
    { term: "Austrāria", meaning: "Australia", romanization: "ow-straa-ree-ah" },
    { term: "Ingarangi", meaning: "England", romanization: "ee-nga-rangi" },
    { term: "Haina", meaning: "China", romanization: "high-na" },
    { term: "Pāina", meaning: "Spain", romanization: "paa-ee-na" },
    { term: "Hōrana", meaning: "Holland / Netherlands", romanization: "haw-ra-na" },
  ],
  culture: [
    { term: "whānau", meaning: "extended family", romanization: "faa-now" },
    { term: "mana", meaning: "prestige / authority", romanization: "ma-na" },
    { term: "tapu", meaning: "sacred / restricted", romanization: "ta-poo" },
    { term: "marae", meaning: "communal meeting place", romanization: "ma-rye" },
    { term: "hongi", meaning: "press noses in greeting", romanization: "hong-ee" },
    { term: "tikanga", meaning: "customs / correct practice", romanization: "tee-kang-ah" },
  ],
  medical: [
    { term: "hōhipera", meaning: "hospital", romanization: "haw-hee-peh-ra" },
    { term: "mamae", meaning: "pain / sore", romanization: "ma-mye" },
    { term: "rongoā", meaning: "medicine / healing", romanization: "rongo-aah" },
    { term: "māuiui", meaning: "sick", romanization: "maa-oo-ee-oo-ee" },
    { term: "ora", meaning: "well / alive / healthy", romanization: "o-ra" },
    { term: "omatangi", meaning: "emergency (urgent)", romanization: "o-ma-tangi" },
  ],
  politics: [
    { term: "pōti", meaning: "vote", romanization: "paw-tee" },
    { term: "ture", meaning: "law", romanization: "too-reh" },
    { term: "kāwanatanga", meaning: "government", romanization: "kaa-wa-na-tang-ah" },
    { term: "tika", meaning: "right / correct / justice", romanization: "tee-ka" },
    { term: "rangatiratanga", meaning: "chieftainship / self-determination", romanization: "ra-nga-tee-ra-tang-ah" },
    { term: "Tiriti", meaning: "Treaty (of Waitangi)", romanization: "tee-ree-tee" },
  ],
  technology: [
    { term: "rorohiko", meaning: "computer", romanization: "ro-ro-hee-ko" },
    { term: "waea", meaning: "phone / call", romanization: "wye-ah" },
    { term: "ipurangi", meaning: "internet", romanization: "ee-poo-rangi" },
    { term: "īmēra", meaning: "email", romanization: "ee-meh-ra" },
    { term: "ataata", meaning: "video", romanization: "a-ta-a-ta" },
    { term: "kupuhipa", meaning: "password", romanization: "koo-poo-hee-pa" },
  ],
  psychology: [
    { term: "hinengaro", meaning: "mind / psychological", romanization: "hee-neng-ah-ro" },
    { term: "whakaaro", meaning: "thought / opinion", romanization: "fa-kaa-ro" },
    { term: "maumahara", meaning: "remember", romanization: "mow-ma-ha-ra" },
    { term: "wareware", meaning: "forget", romanization: "wa-reh-wa-reh" },
    { term: "āhurutanga", meaning: "sense of safety / comfort", romanization: "aah-hoo-roo-tang-ah" },
    { term: "tau", meaning: "settled / calm", romanization: "tow" },
  ],
  speaking: [
    { term: "kia ora", meaning: "hello / be well", romanization: "kee-ah o-ra" },
    { term: "tēnā koe", meaning: "hello (to one)", romanization: "teh-naa ko-eh" },
    { term: "ngā mihi", meaning: "thanks / acknowledgements", romanization: "ngaa mee-hee" },
    { term: "aumārie", meaning: "please (softener) / gentle", romanization: "ow-maa-ree-eh" },
    { term: "whakapāha", meaning: "apology / sorry", romanization: "fa-ka-paa-ha" },
    { term: "āe / kāo", meaning: "yes / no", romanization: "aah-eh / kaa-o" },
  ],
  reading: [
    { term: "pānui", meaning: "read / notice", romanization: "paa-noo-ee" },
    { term: "kōrero", meaning: "story / talk", romanization: "koo-reh-ro" },
    { term: "rerenga kōrero", meaning: "sentence", romanization: "reh-renga koo-reh-ro" },
    { term: "kupu", meaning: "word", romanization: "koo-poo" },
    { term: "taitara", meaning: "title", romanization: "tye-ta-ra" },
    { term: "pukapuka", meaning: "book", romanization: "poo-ka-poo-ka" },
  ],
  writing: [
    { term: "tuhituhi", meaning: "write", romanization: "too-hee-too-hee" },
    { term: "reta", meaning: "letter", romanization: "reh-ta" },
    { term: "rārangi", meaning: "list / line", romanization: "raa-ra-ngi" },
    { term: "tuhipoka", meaning: "note", romanization: "too-hee-po-ka" },
    { term: "kupu tā", meaning: "typed word / print", romanization: "koo-poo taa" },
    { term: "tohutō", meaning: "macron", romanization: "to-hoo-taw" },
  ],
  translating: [
    { term: "whakamāori", meaning: "translate into Māori", romanization: "fa-ka-maa-o-ree" },
    { term: "tikanga", meaning: "meaning / custom", romanization: "tee-kang-ah" },
    { term: "ōrite", meaning: "same / equal", romanization: "o-ree-teh" },
    { term: "rerekē", meaning: "different", romanization: "reh-reh-keh" },
    { term: "tauira", meaning: "example / student", romanization: "tow-ee-ra" },
    { term: "whakataurite", meaning: "compare", romanization: "fa-ka-tow-ree-teh" },
  ],
  slang: [
    { term: "bro / cuz", meaning: "mate (NZ informal English)", hint: "Often mixed in speech", note: "Informal NZ English contact" },
    { term: "chur", meaning: "thanks / respect (NZ slang)", hint: "Informal", note: "Casual gratitude" },
    { term: "sweet as", meaning: "all good", hint: "NZ English", note: "Very common informal" },
    { term: "e hoa", meaning: "friend (address)", romanization: "eh for-ah", note: "Friendly informal" },
    { term: "kai time", meaning: "time to eat (mixed)", hint: "Code-switch", note: "Informal bilingual" },
    { term: "stink", meaning: "bad / unfair (slang)", hint: "NZ informal", note: "Mild negative slang" },
  ],
  quotes: [
    { term: "He aha te mea nui? He tangata", meaning: "What is the most important thing? It is people", hint: "Famous proverb" },
    { term: "Whāia te iti kahurangi", meaning: "Pursue the treasured goal", hint: "Aspiration proverb" },
    { term: "Naku te rourou...", meaning: "With your basket and mine, the people will thrive", hint: "Sharing proverb" },
    { term: "Titiro whakamuri, kōkiri whakamua", meaning: "Look back, strive forward", hint: "Learning proverb" },
    { term: "Ahakoa he iti, he pounamu", meaning: "Although small, it is a treasure", hint: "Value proverb" },
    { term: "Kia kaha", meaning: "Be strong", hint: "Common encouragement" },
  ],
  media: [
    { term: "kiriata", meaning: "movie / film", romanization: "kee-ree-ah-ta" },
    { term: "pouaka whakaata", meaning: "television", romanization: "po-oo-ah-ka fa-kaa-a-ta" },
    { term: "pukapuka", meaning: "book", romanization: "poo-ka-poo-ka" },
    { term: "kaiwhakaari", meaning: "actor", romanization: "kye-fa-kaa-a-ree" },
    { term: "waiata", meaning: "song", romanization: "wye-ah-ta" },
    { term: "kupu hāora", meaning: "subtitles / captions", romanization: "koo-poo haa-o-ra" },
  ],
};

const mandarin: Bank = {
  grammar: [
    { term: "SVO", meaning: "Subject-Verb-Object order", hint: "我爱你" },
    { term: "的 (de)", meaning: "Possessive / modifier particle", hint: "我的书", romanization: "de" },
    { term: "了 (le)", meaning: "Completed action particle", hint: "我吃了", romanization: "le" },
    { term: "吗 (ma)", meaning: "Yes/no question particle", hint: "你好吗？", romanization: "ma" },
    { term: "不 (bù)", meaning: "Negation", hint: "不是", romanization: "bù" },
    { term: "量词", meaning: "Measure words (classifiers)", hint: "一个人", romanization: "liàngcí" },
  ],
  alphabet: [
    { term: "pinyin", meaning: "Romanization system", hint: "nǐ hǎo" },
    { term: "four tones", meaning: "ˉ ˊ ˇ ˋ tone contours", hint: "mā má mǎ mà" },
    { term: "ā", meaning: "First tone — high level", romanization: "ā" },
    { term: "á", meaning: "Second tone — rising", romanization: "á" },
    { term: "ǎ", meaning: "Third tone — low dipping", romanization: "ǎ" },
    { term: "à", meaning: "Fourth tone — falling", romanization: "à" },
  ],
  pronouns: [
    { term: "我", meaning: "I / me", romanization: "wǒ" },
    { term: "你", meaning: "you", romanization: "nǐ" },
    { term: "他 / 她", meaning: "he / she", romanization: "tā" },
    { term: "我们", meaning: "we", romanization: "wǒmen" },
    { term: "他们", meaning: "they", romanization: "tāmen" },
    { term: "您", meaning: "you (polite)", romanization: "nín" },
  ],
  nouns: [
    { term: "家", meaning: "home / family", romanization: "jiā" },
    { term: "水", meaning: "water", romanization: "shuǐ" },
    { term: "人", meaning: "person", romanization: "rén" },
    { term: "名字", meaning: "name", romanization: "míngzi" },
    { term: "书", meaning: "book", romanization: "shū" },
    { term: "学校", meaning: "school", romanization: "xuéxiào" },
  ],
  verbs: [
    { term: "去", meaning: "go", romanization: "qù" },
    { term: "来", meaning: "come", romanization: "lái" },
    { term: "吃", meaning: "eat", romanization: "chī" },
    { term: "喝", meaning: "drink", romanization: "hē" },
    { term: "看", meaning: "look / watch / read", romanization: "kàn" },
    { term: "说", meaning: "speak", romanization: "shuō" },
  ],
  adjectives: [
    { term: "好", meaning: "good", romanization: "hǎo" },
    { term: "坏", meaning: "bad", romanization: "huài" },
    { term: "大", meaning: "big", romanization: "dà" },
    { term: "小", meaning: "small", romanization: "xiǎo" },
    { term: "快", meaning: "fast", romanization: "kuài" },
    { term: "慢", meaning: "slow", romanization: "màn" },
  ],
  colors: [
    { term: "红色", meaning: "red", romanization: "hóngsè" },
    { term: "蓝色", meaning: "blue", romanization: "lánsè" },
    { term: "绿色", meaning: "green", romanization: "lǜsè" },
    { term: "黄色", meaning: "yellow", romanization: "huángsè" },
    { term: "黑色", meaning: "black", romanization: "hēisè" },
    { term: "白色", meaning: "white", romanization: "báisè" },
  ],
  maths: [
    { term: "一", meaning: "one", romanization: "yī" },
    { term: "二", meaning: "two", romanization: "èr" },
    { term: "三", meaning: "three", romanization: "sān" },
    { term: "五", meaning: "five", romanization: "wǔ" },
    { term: "十", meaning: "ten", romanization: "shí" },
    { term: "加", meaning: "plus / add", romanization: "jiā" },
  ],
  time: [
    { term: "现在", meaning: "now", romanization: "xiànzài" },
    { term: "明天", meaning: "tomorrow", romanization: "míngtiān" },
    { term: "昨天", meaning: "yesterday", romanization: "zuótiān" },
    { term: "星期", meaning: "week / weekday", romanization: "xīngqī" },
    { term: "月", meaning: "month / moon", romanization: "yuè" },
    { term: "时间", meaning: "time", romanization: "shíjiān" },
  ],
  emotions: [
    { term: "高兴", meaning: "happy", romanization: "gāoxìng" },
    { term: "难过", meaning: "sad", romanization: "nánguò" },
    { term: "生气", meaning: "angry", romanization: "shēngqì" },
    { term: "害怕", meaning: "afraid", romanization: "hàipà" },
    { term: "爱", meaning: "love", romanization: "ài" },
    { term: "累", meaning: "tired", romanization: "lèi" },
  ],
  body: [
    { term: "头", meaning: "head", romanization: "tóu" },
    { term: "眼睛", meaning: "eyes", romanization: "yǎnjing" },
    { term: "手", meaning: "hand", romanization: "shǒu" },
    { term: "脚", meaning: "foot", romanization: "jiǎo" },
    { term: "心", meaning: "heart", romanization: "xīn" },
    { term: "耳朵", meaning: "ear", romanization: "ěrduo" },
  ],
  senses: [
    { term: "看", meaning: "see / look", romanization: "kàn" },
    { term: "听", meaning: "hear / listen", romanization: "tīng" },
    { term: "摸", meaning: "touch", romanization: "mō" },
    { term: "闻", meaning: "smell", romanization: "wén" },
    { term: "尝", meaning: "taste", romanization: "cháng" },
    { term: "感觉", meaning: "feel / sense", romanization: "gǎnjué" },
  ],
  clothing: [
    { term: "衣服", meaning: "clothes", romanization: "yīfu" },
    { term: "鞋子", meaning: "shoes", romanization: "xiézi" },
    { term: "帽子", meaning: "hat", romanization: "màozi" },
    { term: "衬衫", meaning: "shirt", romanization: "chènshān" },
    { term: "裤子", meaning: "pants", romanization: "kùzi" },
    { term: "外套", meaning: "coat / jacket", romanization: "wàitào" },
  ],
  food: [
    { term: "饭", meaning: "meal / rice", romanization: "fàn" },
    { term: "水", meaning: "water", romanization: "shuǐ" },
    { term: "茶", meaning: "tea", romanization: "chá" },
    { term: "面包", meaning: "bread", romanization: "miànbāo" },
    { term: "苹果", meaning: "apple", romanization: "píngguǒ" },
    { term: "咖啡", meaning: "coffee", romanization: "kāfēi" },
  ],
  animals: [
    { term: "狗", meaning: "dog", romanization: "gǒu" },
    { term: "猫", meaning: "cat", romanization: "māo" },
    { term: "鸟", meaning: "bird", romanization: "niǎo" },
    { term: "鱼", meaning: "fish", romanization: "yú" },
    { term: "马", meaning: "horse", romanization: "mǎ" },
    { term: "龙", meaning: "dragon", romanization: "lóng" },
  ],
  furniture: [
    { term: "椅子", meaning: "chair", romanization: "yǐzi" },
    { term: "桌子", meaning: "table", romanization: "zhuōzi" },
    { term: "床", meaning: "bed", romanization: "chuáng" },
    { term: "门", meaning: "door", romanization: "mén" },
    { term: "窗户", meaning: "window", romanization: "chuānghu" },
    { term: "灯", meaning: "lamp", romanization: "dēng" },
  ],
  occupations: [
    { term: "老师", meaning: "teacher", romanization: "lǎoshī" },
    { term: "医生", meaning: "doctor", romanization: "yīshēng" },
    { term: "护士", meaning: "nurse", romanization: "hùshi" },
    { term: "警察", meaning: "police", romanization: "jǐngchá" },
    { term: "厨师", meaning: "chef", romanization: "chúshī" },
    { term: "学生", meaning: "student", romanization: "xuéshēng" },
  ],
  school: [
    { term: "学校", meaning: "school", romanization: "xuéxiào" },
    { term: "作业", meaning: "homework", romanization: "zuòyè" },
    { term: "考试", meaning: "test / exam", romanization: "kǎoshì" },
    { term: "问题", meaning: "question / problem", romanization: "wèntí" },
    { term: "答案", meaning: "answer", romanization: "dá'àn" },
    { term: "学习", meaning: "study / learn", romanization: "xuéxí" },
  ],
  travel: [
    { term: "哪里", meaning: "where", romanization: "nǎlǐ" },
    { term: "这里", meaning: "here", romanization: "zhèlǐ" },
    { term: "左", meaning: "left", romanization: "zuǒ" },
    { term: "右", meaning: "right", romanization: "yòu" },
    { term: "飞机", meaning: "airplane", romanization: "fēijī" },
    { term: "火车", meaning: "train", romanization: "huǒchē" },
  ],
  countries: [
    { term: "中国", meaning: "China", romanization: "Zhōngguó" },
    { term: "美国", meaning: "USA", romanization: "Měiguó" },
    { term: "英国", meaning: "UK", romanization: "Yīngguó" },
    { term: "西班牙", meaning: "Spain", romanization: "Xībānyá" },
    { term: "荷兰", meaning: "Netherlands", romanization: "Hélán" },
    { term: "新西兰", meaning: "New Zealand", romanization: "Xīnxīlán" },
  ],
  culture: [
    { term: "春节", meaning: "Spring Festival / Lunar New Year", romanization: "Chūnjié" },
    { term: "茶", meaning: "tea culture", romanization: "chá" },
    { term: "书法", meaning: "calligraphy", romanization: "shūfǎ" },
    { term: "面子", meaning: "face / social dignity", romanization: "miànzi" },
    { term: "家庭", meaning: "family", romanization: "jiātíng" },
    { term: "礼貌", meaning: "politeness", romanization: "lǐmào" },
  ],
  medical: [
    { term: "医院", meaning: "hospital", romanization: "yīyuàn" },
    { term: "疼", meaning: "pain / ache", romanization: "téng" },
    { term: "药", meaning: "medicine", romanization: "yào" },
    { term: "病", meaning: "illness", romanization: "bìng" },
    { term: "健康", meaning: "health / healthy", romanization: "jiànkāng" },
    { term: "急诊", meaning: "emergency (medical)", romanization: "jízhěn" },
  ],
  politics: [
    { term: "投票", meaning: "vote", romanization: "tóupiào" },
    { term: "法律", meaning: "law", romanization: "fǎlǜ" },
    { term: "政府", meaning: "government", romanization: "zhèngfǔ" },
    { term: "权利", meaning: "rights", romanization: "quánlì" },
    { term: "和平", meaning: "peace", romanization: "hépíng" },
    { term: "平等", meaning: "equality", romanization: "píngděng" },
  ],
  technology: [
    { term: "电脑", meaning: "computer", romanization: "diànnǎo" },
    { term: "手机", meaning: "mobile phone", romanization: "shǒujī" },
    { term: "互联网", meaning: "internet", romanization: "hùliánwǎng" },
    { term: "邮件", meaning: "email / mail", romanization: "yóujiàn" },
    { term: "视频", meaning: "video", romanization: "shìpín" },
    { term: "密码", meaning: "password", romanization: "mìmǎ" },
  ],
  psychology: [
    { term: "心理", meaning: "psychology / mindset", romanization: "xīnlǐ" },
    { term: "想", meaning: "think / want", romanization: "xiǎng" },
    { term: "记住", meaning: "remember", romanization: "jìzhù" },
    { term: "忘记", meaning: "forget", romanization: "wàngjì" },
    { term: "压力", meaning: "stress / pressure", romanization: "yālì" },
    { term: "放松", meaning: "relax", romanization: "fàngsōng" },
  ],
  speaking: [
    { term: "你好", meaning: "hello", romanization: "nǐ hǎo" },
    { term: "谢谢", meaning: "thank you", romanization: "xièxie" },
    { term: "请", meaning: "please", romanization: "qǐng" },
    { term: "对不起", meaning: "sorry", romanization: "duìbuqǐ" },
    { term: "是", meaning: "yes / to be", romanization: "shì" },
    { term: "不是", meaning: "no / is not", romanization: "bú shì" },
  ],
  reading: [
    { term: "读", meaning: "read", romanization: "dú" },
    { term: "故事", meaning: "story", romanization: "gùshi" },
    { term: "句子", meaning: "sentence", romanization: "jùzi" },
    { term: "词", meaning: "word", romanization: "cí" },
    { term: "标题", meaning: "title", romanization: "biāotí" },
    { term: "汉字", meaning: "Chinese character", romanization: "hànzì" },
  ],
  writing: [
    { term: "写", meaning: "write", romanization: "xiě" },
    { term: "信", meaning: "letter", romanization: "xìn" },
    { term: "列表", meaning: "list", romanization: "lièbiǎo" },
    { term: "笔记", meaning: "notes", romanization: "bǐjì" },
    { term: "笔顺", meaning: "stroke order", romanization: "bǐshùn" },
    { term: "拼音", meaning: "pinyin", romanization: "pīnyīn" },
  ],
  translating: [
    { term: "翻译", meaning: "translate / interpret", romanization: "fānyì" },
    { term: "意思", meaning: "meaning", romanization: "yìsi" },
    { term: "一样", meaning: "the same", romanization: "yíyàng" },
    { term: "不同", meaning: "different", romanization: "bùtóng" },
    { term: "例子", meaning: "example", romanization: "lìzi" },
    { term: "比较", meaning: "compare", romanization: "bǐjiào" },
  ],
  slang: [
    { term: "牛", meaning: "awesome (slang)", romanization: "niú", note: "Informal praise" },
    { term: "靠", meaning: "damn (mild swear)", romanization: "kào", note: "Mild curse — careful" },
    { term: "搞定", meaning: "get it done", romanization: "gǎodìng", note: "Informal" },
    { term: "吃瓜", meaning: "spectate drama", romanization: "chī guā", note: "Internet slang" },
    { term: "郁闷", meaning: "bummed out", romanization: "yùmèn", note: "Informal mood" },
    { term: "废话", meaning: "nonsense", romanization: "fèihuà", note: "Can be rude" },
  ],
  quotes: [
    { term: "学而时习之", meaning: "Learn and review in time", hint: "Analects", romanization: "xué ér shí xí zhī" },
    { term: "一日千里", meaning: "Progress a thousand miles a day", hint: "Rapid progress" },
    { term: "熟能生巧", meaning: "Practice makes skillful", romanization: "shú néng shēng qiǎo" },
    { term: "有志者事竟成", meaning: "Where there's a will, there's a way", romanization: "yǒu zhì zhě shì jìng chéng" },
    { term: "授人以渔", meaning: "Teach fishing, not just give fish", hint: "Education proverb" },
    { term: "千里之行，始于足下", meaning: "A journey of a thousand miles begins with one step", romanization: "qiān lǐ zhī xíng" },
  ],
  media: [
    { term: "电影", meaning: "movie", romanization: "diànyǐng" },
    { term: "电视", meaning: "TV", romanization: "diànshì" },
    { term: "书", meaning: "book", romanization: "shū" },
    { term: "演员", meaning: "actor", romanization: "yǎnyuán" },
    { term: "音乐", meaning: "music", romanization: "yīnyuè" },
    { term: "字幕", meaning: "subtitles", romanization: "zìmù" },
  ],
};

const latin: Bank = {
  grammar: [
    { term: "cases", meaning: "Noun endings show role (nom, acc…)", hint: "Latin is highly inflected" },
    { term: "nominative", meaning: "Subject case", hint: "puella cantat" },
    { term: "accusative", meaning: "Direct object case", hint: "puellam video" },
    { term: "conjugation", meaning: "Verb ending patterns", hint: "amo, amas, amat" },
    { term: "gender", meaning: "masculine, feminine, neuter", hint: "noun agreement" },
    { term: "SOV tendency", meaning: "Verb often at end", hint: "Puella librum legit" },
  ],
  alphabet: [
    { term: "A B C", meaning: "Latin alphabet base of English", hint: "No j/u originally as distinct" },
    { term: "V as U/W", meaning: "Classical V sound varied", hint: "veni ≈ weni" },
    { term: "C as K", meaning: "Hard C in classical", hint: "Caesar ≈ Kaiser-ish" },
    { term: "AE diphthong", meaning: "Like ai in aisle", hint: "saepe" },
    { term: "long vs short", meaning: "Vowel length changes meaning", hint: "malum vs mālum" },
    { term: "macron", meaning: "Marks long vowels in textbooks", hint: "ā ē ī ō ū" },
  ],
  pronouns: [
    { term: "ego", meaning: "I" },
    { term: "tu", meaning: "you (singular)" },
    { term: "is / ea / id", meaning: "he / she / it" },
    { term: "nos", meaning: "we" },
    { term: "vos", meaning: "you (plural)" },
    { term: "meus", meaning: "my / mine" },
  ],
  nouns: [
    { term: "aqua", meaning: "water" },
    { term: "domus", meaning: "house / home" },
    { term: "liber", meaning: "book" },
    { term: "nomen", meaning: "name" },
    { term: "puella", meaning: "girl" },
    { term: "vir", meaning: "man" },
  ],
  verbs: [
    { term: "amo", meaning: "I love" },
    { term: "video", meaning: "I see" },
    { term: "audio", meaning: "I hear" },
    { term: "eo / ire", meaning: "go" },
    { term: "edo / esse", meaning: "eat (edo) / be (esse)", hint: "Don't confuse esse forms" },
    { term: "dico", meaning: "I say" },
  ],
  adjectives: [
    { term: "bonus", meaning: "good" },
    { term: "malus", meaning: "bad" },
    { term: "magnus", meaning: "big / great" },
    { term: "parvus", meaning: "small" },
    { term: "novus", meaning: "new" },
    { term: "antiquus", meaning: "old / ancient" },
  ],
  colors: [
    { term: "ruber", meaning: "red" },
    { term: "caeruleus", meaning: "blue" },
    { term: "viridis", meaning: "green" },
    { term: "flavus", meaning: "yellow" },
    { term: "niger", meaning: "black" },
    { term: "albus", meaning: "white" },
  ],
  maths: [
    { term: "unus", meaning: "one" },
    { term: "duo", meaning: "two" },
    { term: "tres", meaning: "three" },
    { term: "quinque", meaning: "five" },
    { term: "decem", meaning: "ten" },
    { term: "plus", meaning: "more / plus" },
  ],
  time: [
    { term: "nunc", meaning: "now" },
    { term: "cras", meaning: "tomorrow" },
    { term: "heri", meaning: "yesterday" },
    { term: "dies", meaning: "day" },
    { term: "mensis", meaning: "month" },
    { term: "tempus", meaning: "time" },
  ],
  emotions: [
    { term: "laetus", meaning: "happy" },
    { term: "tristis", meaning: "sad" },
    { term: "iratus", meaning: "angry" },
    { term: "timidus", meaning: "afraid / timid" },
    { term: "amor", meaning: "love" },
    { term: "spes", meaning: "hope" },
  ],
  body: [
    { term: "caput", meaning: "head" },
    { term: "oculus", meaning: "eye" },
    { term: "manus", meaning: "hand" },
    { term: "pes", meaning: "foot" },
    { term: "cor", meaning: "heart" },
    { term: "auris", meaning: "ear" },
  ],
  senses: [
    { term: "video", meaning: "I see" },
    { term: "audio", meaning: "I hear" },
    { term: "tango", meaning: "I touch" },
    { term: "olfacio", meaning: "I smell" },
    { term: "gusto", meaning: "I taste" },
    { term: "sentio", meaning: "I feel / perceive" },
  ],
  clothing: [
    { term: "toga", meaning: "Roman outer garment" },
    { term: "tunica", meaning: "tunic" },
    { term: "calceus", meaning: "shoe" },
    { term: "pallium", meaning: "cloak" },
    { term: "vestis", meaning: "clothing" },
    { term: "corona", meaning: "crown / garland" },
  ],
  food: [
    { term: "panis", meaning: "bread" },
    { term: "vinum", meaning: "wine" },
    { term: "aqua", meaning: "water" },
    { term: "caseus", meaning: "cheese" },
    { term: "fructus", meaning: "fruit" },
    { term: "caro", meaning: "meat / flesh" },
  ],
  animals: [
    { term: "canis", meaning: "dog" },
    { term: "feles", meaning: "cat" },
    { term: "avis", meaning: "bird" },
    { term: "piscis", meaning: "fish" },
    { term: "equus", meaning: "horse" },
    { term: "lupus", meaning: "wolf" },
  ],
  furniture: [
    { term: "sella", meaning: "chair / seat" },
    { term: "mensa", meaning: "table" },
    { term: "lectus", meaning: "bed / couch" },
    { term: "ianua", meaning: "door" },
    { term: "fenestra", meaning: "window" },
    { term: "lucerna", meaning: "lamp" },
  ],
  occupations: [
    { term: "magister", meaning: "teacher / master" },
    { term: "medicus", meaning: "doctor" },
    { term: "miles", meaning: "soldier" },
    { term: "poeta", meaning: "poet" },
    { term: "agricola", meaning: "farmer" },
    { term: "servus", meaning: "enslaved person / servant", note: "Historical term — discuss context" },
  ],
  school: [
    { term: "ludus", meaning: "school / game" },
    { term: "discipulus", meaning: "student" },
    { term: "liber", meaning: "book" },
    { term: "quaestio", meaning: "question" },
    { term: "responsum", meaning: "answer" },
    { term: "doceo", meaning: "I teach" },
  ],
  travel: [
    { term: "ubi", meaning: "where" },
    { term: "hic", meaning: "here" },
    { term: "sinister", meaning: "left" },
    { term: "dexter", meaning: "right" },
    { term: "via", meaning: "road / way" },
    { term: "iter", meaning: "journey" },
  ],
  countries: [
    { term: "Roma", meaning: "Rome" },
    { term: "Italia", meaning: "Italy" },
    { term: "Gallia", meaning: "Gaul / France region" },
    { term: "Hispania", meaning: "Spain" },
    { term: "Graecia", meaning: "Greece" },
    { term: "Britannia", meaning: "Britain" },
  ],
  culture: [
    { term: "forum", meaning: "public square / marketplace" },
    { term: "senatus", meaning: "senate" },
    { term: "deus / dea", meaning: "god / goddess" },
    { term: "religio", meaning: "religious practice / obligation" },
    { term: "familia", meaning: "household / family" },
    { term: "virtus", meaning: "virtue / courage" },
  ],
  medical: [
    { term: "valetudo", meaning: "health" },
    { term: "dolor", meaning: "pain" },
    { term: "medicamen", meaning: "medicine / remedy" },
    { term: "aeger", meaning: "sick" },
    { term: "sanus", meaning: "healthy" },
    { term: "vulnus", meaning: "wound" },
  ],
  politics: [
    { term: "rex", meaning: "king" },
    { term: "lex", meaning: "law" },
    { term: "populus", meaning: "the people" },
    { term: "imperium", meaning: "command / empire" },
    { term: "pax", meaning: "peace" },
    { term: "libertas", meaning: "freedom" },
  ],
  technology: [
    { term: "machina", meaning: "machine / device" },
    { term: "rota", meaning: "wheel" },
    { term: "aquaeductus", meaning: "aqueduct" },
    { term: "horologium", meaning: "clock / sundial" },
    { term: "codex", meaning: "bound book / code" },
    { term: "instrumentum", meaning: "tool / instrument" },
  ],
  psychology: [
    { term: "mens", meaning: "mind" },
    { term: "cogito", meaning: "I think" },
    { term: "memoria", meaning: "memory" },
    { term: "oblivio", meaning: "forgetfulness" },
    { term: "anxietas", meaning: "anxiety" },
    { term: "tranquillitas", meaning: "calm" },
  ],
  speaking: [
    { term: "salve", meaning: "hello (to one)" },
    { term: "salvete", meaning: "hello (to many)" },
    { term: "gratias", meaning: "thanks" },
    { term: "amabo te", meaning: "please (literally 'I will love you')" },
    { term: "ignosce", meaning: "forgive / excuse me" },
    { term: "ita / minime", meaning: "yes / no (approx.)" },
  ],
  reading: [
    { term: "lego", meaning: "I read / choose" },
    { term: "fabula", meaning: "story" },
    { term: "sententia", meaning: "sentence / opinion" },
    { term: "verbum", meaning: "word" },
    { term: "titulus", meaning: "title / inscription" },
    { term: "carmen", meaning: "poem / song" },
  ],
  writing: [
    { term: "scribo", meaning: "I write" },
    { term: "epistula", meaning: "letter" },
    { term: "nota", meaning: "note / mark" },
    { term: "tabula", meaning: "tablet / list" },
    { term: "stilus", meaning: "writing stylus" },
    { term: "littera", meaning: "letter (of alphabet)" },
  ],
  translating: [
    { term: "interpretor", meaning: "I explain / translate" },
    { term: "significatio", meaning: "meaning" },
    { term: "idem", meaning: "the same" },
    { term: "alius", meaning: "other / different" },
    { term: "exemplum", meaning: "example" },
    { term: "confero", meaning: "I compare / bring together" },
  ],
  slang: [
    { term: "edepol", meaning: "by Pollux! (mild oath)", note: "Classical mild swear" },
    { term: "hercle", meaning: "by Hercules!", note: "Emphatic mild oath" },
    { term: "vae", meaning: "alas! / woe", note: "Exclamation" },
    { term: "stultus", meaning: "foolish (insult)", note: "Rude if directed at someone" },
    { term: "tace", meaning: "be quiet!", note: "Can be harsh" },
    { term: "apage", meaning: "away! / get lost", note: "Dismissive" },
  ],
  quotes: [
    { term: "Veni, vidi, vici", meaning: "I came, I saw, I conquered", hint: "Caesar" },
    { term: "Carpe diem", meaning: "Seize the day", hint: "Horace" },
    { term: "Cogito, ergo sum", meaning: "I think, therefore I am", hint: "Descartes (Neo-Latin)" },
    { term: "Alea iacta est", meaning: "The die is cast", hint: "Caesar" },
    { term: "Festina lente", meaning: "Make haste slowly", hint: "Proverb" },
    { term: "In vino veritas", meaning: "In wine, truth", hint: "Saying" },
  ],
  media: [
    { term: "fabula", meaning: "story / play" },
    { term: "theatrum", meaning: "theatre" },
    { term: "liber", meaning: "book" },
    { term: "histrio", meaning: "actor" },
    { term: "musica", meaning: "music" },
    { term: "spectaculum", meaning: "show / spectacle" },
  ],
};

const dutch: Bank = {
  grammar: [
    { term: "SVO", meaning: "Main clauses: subject-verb-object", hint: "Ik eet brood" },
    { term: "V2", meaning: "Verb often in second position", hint: "Vandaag eet ik" },
    { term: "de / het", meaning: "Common vs neuter articles", hint: "de man, het huis" },
    { term: "niet / geen", meaning: "not / no (negation types)", hint: "Ik eet niet / geen brood" },
    { term: "separable verbs", meaning: "Prefix can split off", hint: "Ik sta op" },
    { term: "plural -en/-s", meaning: "Noun plural patterns", hint: "boeken, auto's" },
  ],
  alphabet: [
    { term: "A B C", meaning: "Dutch uses Latin letters", hint: "plus digraphs" },
    { term: "ij", meaning: "Common digraph, like ey", hint: "bijt" },
    { term: "ui", meaning: "Unique diphthong", hint: "huis" },
    { term: "g / ch", meaning: "Guttural fricative", hint: "goed, acht" },
    { term: "ee / oo", meaning: "Long vowels", hint: "meer, boom" },
    { term: "stress", meaning: "Usually first syllable", hint: "WOordenboek" },
  ],
  pronouns: [
    { term: "ik", meaning: "I" },
    { term: "jij / je", meaning: "you (informal)" },
    { term: "u", meaning: "you (formal)" },
    { term: "hij / zij / het", meaning: "he / she / it" },
    { term: "wij / we", meaning: "we" },
    { term: "zij / ze", meaning: "they" },
  ],
  nouns: [
    { term: "huis", meaning: "house" },
    { term: "water", meaning: "water" },
    { term: "mens", meaning: "human / person" },
    { term: "naam", meaning: "name" },
    { term: "boek", meaning: "book" },
    { term: "school", meaning: "school" },
  ],
  verbs: [
    { term: "gaan", meaning: "to go" },
    { term: "komen", meaning: "to come" },
    { term: "eten", meaning: "to eat" },
    { term: "drinken", meaning: "to drink" },
    { term: "kijken", meaning: "to look / watch" },
    { term: "spreken", meaning: "to speak" },
  ],
  adjectives: [
    { term: "goed", meaning: "good" },
    { term: "slecht", meaning: "bad" },
    { term: "groot", meaning: "big" },
    { term: "klein", meaning: "small" },
    { term: "snel", meaning: "fast" },
    { term: "langzaam", meaning: "slow" },
  ],
  colors: [
    { term: "rood", meaning: "red" },
    { term: "blauw", meaning: "blue" },
    { term: "groen", meaning: "green" },
    { term: "geel", meaning: "yellow" },
    { term: "zwart", meaning: "black" },
    { term: "wit", meaning: "white" },
  ],
  maths: [
    { term: "een", meaning: "one" },
    { term: "twee", meaning: "two" },
    { term: "drie", meaning: "three" },
    { term: "vijf", meaning: "five" },
    { term: "tien", meaning: "ten" },
    { term: "plus", meaning: "plus" },
  ],
  time: [
    { term: "nu", meaning: "now" },
    { term: "morgen", meaning: "tomorrow / morning" },
    { term: "gisteren", meaning: "yesterday" },
    { term: "week", meaning: "week" },
    { term: "maand", meaning: "month" },
    { term: "tijd", meaning: "time" },
  ],
  emotions: [
    { term: "blij", meaning: "happy" },
    { term: "verdrietig", meaning: "sad" },
    { term: "boos", meaning: "angry" },
    { term: "bang", meaning: "afraid" },
    { term: "liefde", meaning: "love" },
    { term: "moe", meaning: "tired" },
  ],
  body: [
    { term: "hoofd", meaning: "head" },
    { term: "oog", meaning: "eye" },
    { term: "hand", meaning: "hand" },
    { term: "voet", meaning: "foot" },
    { term: "hart", meaning: "heart" },
    { term: "oor", meaning: "ear" },
  ],
  senses: [
    { term: "zien", meaning: "to see" },
    { term: "horen", meaning: "to hear" },
    { term: "voelen", meaning: "to feel / touch" },
    { term: "ruiken", meaning: "to smell" },
    { term: "proeven", meaning: "to taste" },
    { term: "luisteren", meaning: "to listen" },
  ],
  clothing: [
    { term: "kleren", meaning: "clothes" },
    { term: "schoenen", meaning: "shoes" },
    { term: "hoed", meaning: "hat" },
    { term: "shirt", meaning: "shirt" },
    { term: "broek", meaning: "pants" },
    { term: "jas", meaning: "coat / jacket" },
  ],
  food: [
    { term: "brood", meaning: "bread" },
    { term: "water", meaning: "water" },
    { term: "melk", meaning: "milk" },
    { term: "kaas", meaning: "cheese" },
    { term: "appel", meaning: "apple" },
    { term: "koffie", meaning: "coffee" },
  ],
  animals: [
    { term: "hond", meaning: "dog" },
    { term: "kat", meaning: "cat" },
    { term: "vogel", meaning: "bird" },
    { term: "vis", meaning: "fish" },
    { term: "paard", meaning: "horse" },
    { term: "koe", meaning: "cow" },
  ],
  furniture: [
    { term: "stoel", meaning: "chair" },
    { term: "tafel", meaning: "table" },
    { term: "bed", meaning: "bed" },
    { term: "deur", meaning: "door" },
    { term: "raam", meaning: "window" },
    { term: "lamp", meaning: "lamp" },
  ],
  occupations: [
    { term: "leraar", meaning: "teacher" },
    { term: "dokter", meaning: "doctor" },
    { term: "verpleegkundige", meaning: "nurse" },
    { term: "politie", meaning: "police" },
    { term: "kok", meaning: "chef / cook" },
    { term: "kunstenaar", meaning: "artist" },
  ],
  school: [
    { term: "school", meaning: "school" },
    { term: "leerling", meaning: "pupil / student" },
    { term: "huiswerk", meaning: "homework" },
    { term: "toets", meaning: "test" },
    { term: "vraag", meaning: "question" },
    { term: "antwoord", meaning: "answer" },
  ],
  travel: [
    { term: "waar", meaning: "where" },
    { term: "hier", meaning: "here" },
    { term: "links", meaning: "left" },
    { term: "rechts", meaning: "right" },
    { term: "vliegtuig", meaning: "airplane" },
    { term: "trein", meaning: "train" },
  ],
  countries: [
    { term: "Nederland", meaning: "the Netherlands" },
    { term: "België", meaning: "Belgium" },
    { term: "Duitsland", meaning: "Germany" },
    { term: "Spanje", meaning: "Spain" },
    { term: "China", meaning: "China" },
    { term: "Nieuw-Zeeland", meaning: "New Zealand" },
  ],
  culture: [
    { term: "gezellig", meaning: "cozy / sociable vibe", hint: "Untranslatable classic" },
    { term: "oranje", meaning: "orange (national color)" },
    { term: "fiets", meaning: "bicycle" },
    { term: "koningsdag", meaning: "King's Day" },
    { term: "polder", meaning: "reclaimed land" },
    { term: "tolerantie", meaning: "tolerance" },
  ],
  medical: [
    { term: "ziekenhuis", meaning: "hospital" },
    { term: "pijn", meaning: "pain" },
    { term: "medicijn", meaning: "medicine" },
    { term: "ziek", meaning: "sick" },
    { term: "gezond", meaning: "healthy" },
    { term: "spoed", meaning: "emergency / urgency" },
  ],
  politics: [
    { term: "stemmen", meaning: "to vote" },
    { term: "wet", meaning: "law" },
    { term: "regering", meaning: "government" },
    { term: "rechten", meaning: "rights" },
    { term: "vrede", meaning: "peace" },
    { term: "democratie", meaning: "democracy" },
  ],
  technology: [
    { term: "computer", meaning: "computer" },
    { term: "telefoon", meaning: "phone" },
    { term: "internet", meaning: "internet" },
    { term: "e-mail", meaning: "email" },
    { term: "video", meaning: "video" },
    { term: "wachtwoord", meaning: "password" },
  ],
  psychology: [
    { term: "geest", meaning: "mind / spirit" },
    { term: "denken", meaning: "to think" },
    { term: "onthouden", meaning: "to remember" },
    { term: "vergeten", meaning: "to forget" },
    { term: "stress", meaning: "stress" },
    { term: "kalm", meaning: "calm" },
  ],
  speaking: [
    { term: "hallo", meaning: "hello" },
    { term: "dank je", meaning: "thank you" },
    { term: "alsjeblieft", meaning: "please / here you go" },
    { term: "sorry", meaning: "sorry" },
    { term: "ja", meaning: "yes" },
    { term: "nee", meaning: "no" },
  ],
  reading: [
    { term: "lezen", meaning: "to read" },
    { term: "verhaal", meaning: "story" },
    { term: "zin", meaning: "sentence" },
    { term: "woord", meaning: "word" },
    { term: "titel", meaning: "title" },
    { term: "boek", meaning: "book" },
  ],
  writing: [
    { term: "schrijven", meaning: "to write" },
    { term: "brief", meaning: "letter" },
    { term: "lijst", meaning: "list" },
    { term: "notitie", meaning: "note" },
    { term: "spelling", meaning: "spelling" },
    { term: "zin maken", meaning: "make a sentence" },
  ],
  translating: [
    { term: "vertalen", meaning: "to translate" },
    { term: "betekenis", meaning: "meaning" },
    { term: "hetzelfde", meaning: "the same" },
    { term: "anders", meaning: "different" },
    { term: "voorbeeld", meaning: "example" },
    { term: "vergelijken", meaning: "to compare" },
  ],
  slang: [
    { term: "tof", meaning: "cool", note: "Informal positive" },
    { term: "kut", meaning: "strong swear (vulgar)", note: "Strong curse — avoid casually" },
    { term: "doe normaal", meaning: "act normal / chill out", note: "Very Dutch phrase" },
    { term: "sukkel", meaning: "idiot (insult)", note: "Rude" },
    { term: "leuk", meaning: "nice / fun", note: "Everyday informal" },
    { term: "shit", meaning: "damn (loan swear)", note: "Mild-strong depending on tone" },
  ],
  quotes: [
    { term: "Doe maar gewoon", meaning: "Just act normal", hint: "Cultural motto" },
    { term: "Hoge bomen vangen veel wind", meaning: "Tall trees catch much wind", hint: "Proverb" },
    { term: "Oost west, thuis best", meaning: "East west, home is best", hint: "Proverb" },
    { term: "Wie goed doet, goed ontmoet", meaning: "Do good, meet good", hint: "Proverb" },
    { term: "Al doende leert men", meaning: "One learns by doing", hint: "Proverb" },
    { term: "Beter één vogel in de hand...", meaning: "A bird in the hand is worth two in the bush", hint: "Proverb" },
  ],
  media: [
    { term: "film", meaning: "movie" },
    { term: "televisie", meaning: "TV" },
    { term: "boek", meaning: "book" },
    { term: "acteur", meaning: "actor" },
    { term: "muziek", meaning: "music" },
    { term: "ondertiteling", meaning: "subtitles" },
  ],
};

const spanish: Bank = {
  grammar: [
    { term: "SVO", meaning: "Subject-Verb-Object", hint: "Yo como pan" },
    { term: "gender", meaning: "Nouns are masculine or feminine", hint: "el / la" },
    { term: "ser vs estar", meaning: "Two verbs for 'to be'", hint: "essence vs state" },
    { term: "conjugation", meaning: "Verbs change by person/tense", hint: "hablo, hablas, habla" },
    { term: "no", meaning: "Negation before verb", hint: "No quiero" },
    { term: "questions", meaning: "¿...?", hint: "Inverted marks" },
  ],
  alphabet: [
    { term: "A B C", meaning: "Spanish alphabet", hint: "Includes ñ" },
    { term: "ñ", meaning: "nye sound", hint: "España", romanization: "ny" },
    { term: "rr", meaning: "Trilled r", hint: "perro" },
    { term: "j / g", meaning: "Strong h-like sound", hint: "jardín, gente" },
    { term: "ll / y", meaning: "Often like English y", hint: "llamarse" },
    { term: "stress accent", meaning: "Á é í ó ú mark stress", hint: "café" },
  ],
  pronouns: [
    { term: "yo", meaning: "I" },
    { term: "tú", meaning: "you (informal)" },
    { term: "usted", meaning: "you (formal)" },
    { term: "él / ella", meaning: "he / she" },
    { term: "nosotros", meaning: "we" },
    { term: "ellos / ellas", meaning: "they" },
  ],
  nouns: [
    { term: "casa", meaning: "house" },
    { term: "agua", meaning: "water" },
    { term: "persona", meaning: "person" },
    { term: "nombre", meaning: "name" },
    { term: "libro", meaning: "book" },
    { term: "escuela", meaning: "school" },
  ],
  verbs: [
    { term: "ir", meaning: "to go" },
    { term: "venir", meaning: "to come" },
    { term: "comer", meaning: "to eat" },
    { term: "beber", meaning: "to drink" },
    { term: "mirar", meaning: "to look" },
    { term: "hablar", meaning: "to speak" },
  ],
  adjectives: [
    { term: "bueno", meaning: "good" },
    { term: "malo", meaning: "bad" },
    { term: "grande", meaning: "big" },
    { term: "pequeño", meaning: "small" },
    { term: "rápido", meaning: "fast" },
    { term: "lento", meaning: "slow" },
  ],
  colors: [
    { term: "rojo", meaning: "red" },
    { term: "azul", meaning: "blue" },
    { term: "verde", meaning: "green" },
    { term: "amarillo", meaning: "yellow" },
    { term: "negro", meaning: "black" },
    { term: "blanco", meaning: "white" },
  ],
  maths: [
    { term: "uno", meaning: "one" },
    { term: "dos", meaning: "two" },
    { term: "tres", meaning: "three" },
    { term: "cinco", meaning: "five" },
    { term: "diez", meaning: "ten" },
    { term: "más", meaning: "plus / more" },
  ],
  time: [
    { term: "ahora", meaning: "now" },
    { term: "mañana", meaning: "tomorrow / morning" },
    { term: "ayer", meaning: "yesterday" },
    { term: "semana", meaning: "week" },
    { term: "mes", meaning: "month" },
    { term: "tiempo", meaning: "time / weather" },
  ],
  emotions: [
    { term: "feliz", meaning: "happy" },
    { term: "triste", meaning: "sad" },
    { term: "enojado", meaning: "angry" },
    { term: "asustado", meaning: "afraid" },
    { term: "amor", meaning: "love" },
    { term: "cansado", meaning: "tired" },
  ],
  body: [
    { term: "cabeza", meaning: "head" },
    { term: "ojo", meaning: "eye" },
    { term: "mano", meaning: "hand" },
    { term: "pie", meaning: "foot" },
    { term: "corazón", meaning: "heart" },
    { term: "oreja", meaning: "ear" },
  ],
  senses: [
    { term: "ver", meaning: "to see" },
    { term: "oír", meaning: "to hear" },
    { term: "tocar", meaning: "to touch" },
    { term: "oler", meaning: "to smell" },
    { term: "probar", meaning: "to taste / try" },
    { term: "sentir", meaning: "to feel" },
  ],
  clothing: [
    { term: "ropa", meaning: "clothes" },
    { term: "zapatos", meaning: "shoes" },
    { term: "sombrero", meaning: "hat" },
    { term: "camisa", meaning: "shirt" },
    { term: "pantalones", meaning: "pants" },
    { term: "abrigo", meaning: "coat" },
  ],
  food: [
    { term: "pan", meaning: "bread" },
    { term: "agua", meaning: "water" },
    { term: "leche", meaning: "milk" },
    { term: "queso", meaning: "cheese" },
    { term: "manzana", meaning: "apple" },
    { term: "café", meaning: "coffee" },
  ],
  animals: [
    { term: "perro", meaning: "dog" },
    { term: "gato", meaning: "cat" },
    { term: "pájaro", meaning: "bird" },
    { term: "pez", meaning: "fish" },
    { term: "caballo", meaning: "horse" },
    { term: "vaca", meaning: "cow" },
  ],
  furniture: [
    { term: "silla", meaning: "chair" },
    { term: "mesa", meaning: "table" },
    { term: "cama", meaning: "bed" },
    { term: "puerta", meaning: "door" },
    { term: "ventana", meaning: "window" },
    { term: "lámpara", meaning: "lamp" },
  ],
  occupations: [
    { term: "maestro / profesor", meaning: "teacher" },
    { term: "médico", meaning: "doctor" },
    { term: "enfermero", meaning: "nurse" },
    { term: "policía", meaning: "police" },
    { term: "cocinero", meaning: "cook / chef" },
    { term: "artista", meaning: "artist" },
  ],
  school: [
    { term: "escuela", meaning: "school" },
    { term: "estudiante", meaning: "student" },
    { term: "tarea", meaning: "homework" },
    { term: "examen", meaning: "test / exam" },
    { term: "pregunta", meaning: "question" },
    { term: "respuesta", meaning: "answer" },
  ],
  travel: [
    { term: "dónde", meaning: "where" },
    { term: "aquí", meaning: "here" },
    { term: "izquierda", meaning: "left" },
    { term: "derecha", meaning: "right" },
    { term: "avión", meaning: "airplane" },
    { term: "tren", meaning: "train" },
  ],
  countries: [
    { term: "España", meaning: "Spain" },
    { term: "México", meaning: "Mexico" },
    { term: "Argentina", meaning: "Argentina" },
    { term: "China", meaning: "China" },
    { term: "Países Bajos", meaning: "Netherlands" },
    { term: "Nueva Zelanda", meaning: "New Zealand" },
  ],
  culture: [
    { term: "siesta", meaning: "afternoon rest" },
    { term: "fiesta", meaning: "party / festival" },
    { term: "familia", meaning: "family" },
    { term: "tapas", meaning: "small shared dishes" },
    { term: "flamenco", meaning: "Andalusian music/dance" },
    { term: "respeto", meaning: "respect" },
  ],
  medical: [
    { term: "hospital", meaning: "hospital" },
    { term: "dolor", meaning: "pain" },
    { term: "medicina", meaning: "medicine" },
    { term: "enfermo", meaning: "sick" },
    { term: "salud", meaning: "health" },
    { term: "emergencia", meaning: "emergency" },
  ],
  politics: [
    { term: "votar", meaning: "to vote" },
    { term: "ley", meaning: "law" },
    { term: "gobierno", meaning: "government" },
    { term: "derechos", meaning: "rights" },
    { term: "paz", meaning: "peace" },
    { term: "democracia", meaning: "democracy" },
  ],
  technology: [
    { term: "computadora / ordenador", meaning: "computer" },
    { term: "teléfono", meaning: "phone" },
    { term: "internet", meaning: "internet" },
    { term: "correo", meaning: "email / mail" },
    { term: "video", meaning: "video" },
    { term: "contraseña", meaning: "password" },
  ],
  psychology: [
    { term: "mente", meaning: "mind" },
    { term: "pensar", meaning: "to think" },
    { term: "recordar", meaning: "to remember" },
    { term: "olvidar", meaning: "to forget" },
    { term: "estrés", meaning: "stress" },
    { term: "calma", meaning: "calm" },
  ],
  speaking: [
    { term: "hola", meaning: "hello" },
    { term: "gracias", meaning: "thank you" },
    { term: "por favor", meaning: "please" },
    { term: "perdón / lo siento", meaning: "sorry" },
    { term: "sí", meaning: "yes" },
    { term: "no", meaning: "no" },
  ],
  reading: [
    { term: "leer", meaning: "to read" },
    { term: "historia", meaning: "story / history" },
    { term: "oración", meaning: "sentence / prayer" },
    { term: "palabra", meaning: "word" },
    { term: "título", meaning: "title" },
    { term: "libro", meaning: "book" },
  ],
  writing: [
    { term: "escribir", meaning: "to write" },
    { term: "carta", meaning: "letter" },
    { term: "lista", meaning: "list" },
    { term: "nota", meaning: "note" },
    { term: "ortografía", meaning: "spelling" },
    { term: "acento", meaning: "accent mark" },
  ],
  translating: [
    { term: "traducir", meaning: "to translate" },
    { term: "significado", meaning: "meaning" },
    { term: "igual", meaning: "the same" },
    { term: "diferente", meaning: "different" },
    { term: "ejemplo", meaning: "example" },
    { term: "comparar", meaning: "to compare" },
  ],
  slang: [
    { term: "guay", meaning: "cool (Spain)", note: "Informal Spain" },
    { term: "chévere", meaning: "cool (LatAm)", note: "Informal Latin America" },
    { term: "tío / tía", meaning: "dude (Spain)", note: "Casual address" },
    { term: "mierda", meaning: "shit (swear)", note: "Strong curse — careful" },
    { term: "flipar", meaning: "be amazed / freak out", note: "Informal Spain" },
    { term: "vale", meaning: "okay / alright", note: "Everyday Spain" },
  ],
  quotes: [
    { term: "Más vale tarde que nunca", meaning: "Better late than never", hint: "Proverb" },
    { term: "No hay mal que por bien no venga", meaning: "Every cloud has a silver lining", hint: "Proverb" },
    { term: "El que mucho abarca poco aprieta", meaning: "Don't bite off more than you can chew", hint: "Proverb" },
    { term: "Ojos que no ven, corazón que no siente", meaning: "Out of sight, out of mind", hint: "Proverb" },
    { term: "A quien madruga, Dios le ayuda", meaning: "The early bird gets the worm", hint: "Proverb" },
    { term: "La práctica hace al maestro", meaning: "Practice makes the master", hint: "Proverb" },
  ],
  media: [
    { term: "película", meaning: "movie" },
    { term: "televisión", meaning: "TV" },
    { term: "libro", meaning: "book" },
    { term: "actor / actriz", meaning: "actor / actress" },
    { term: "música", meaning: "music" },
    { term: "subtítulos", meaning: "subtitles" },
  ],
};

export const VOCAB: Record<LanguageId, Bank> = {
  asl: aslBank(),
  bsl: bslBank(),
  isl: islBank(),
  nzsl: nzslBank(),
  maori,
  mandarin,
  latin,
  dutch,
  spanish,
};

function withDefaultCefr(items: VocabItem[], unitId: UnitId): VocabItem[] {
  const fallback: CefrLevel = "A1";
  const unitLevel = UNIT_CEFR[unitId] ?? fallback;
  return items.map((item) => ({
    ...item,
    cefr: item.cefr ?? (unitLevel === "A1" || unitLevel === "A2" ? "A1" : "A2"),
  }));
}

function mergeVocab(base: VocabItem[], extra: VocabItem[]): VocabItem[] {
  const seen = new Set<string>();
  const out: VocabItem[] = [];
  for (const item of [...base, ...extra]) {
    const key = `${item.term.toLowerCase()}::${item.meaning.toLowerCase()}`;
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(item);
  }
  return out;
}

export function getVocab(languageId: LanguageId, unitId: UnitId): VocabItem[] {
  const base = withDefaultCefr(VOCAB[languageId][unitId] ?? [], unitId);
  const tiers = TIER_BANKS[languageId]?.[unitId] ?? [];
  const extras = EXTRA_VOCAB[languageId]?.[unitId] ?? [];
  return mergeVocab(mergeVocab(base, tiers), extras);
}

export function getVocabByCefr(
  languageId: LanguageId,
  unitId: UnitId,
  cefr: CefrLevel,
): VocabItem[] {
  return getVocab(languageId, unitId).filter((v) => (v.cefr ?? "A1") === cefr);
}
