import type { UnitDef } from "./types";

/** Pedagogical order: foundations → words → daily life → society → skills → media */
export const UNITS: UnitDef[] = [
  {
    id: "grammar",
    title: "Grammar",
    subtitle: "How the language fits together",
    icon: "📐",
    color: "#007AFF",
  },
  {
    id: "alphabet",
    title: "Alphabet & Sounds",
    subtitle: "Letters, fingerspelling, and phonetics",
    icon: "🔤",
    color: "#34C759",
  },
  {
    id: "pronouns",
    title: "Pronouns",
    subtitle: "I, you, we, they — and pointing",
    icon: "👆",
    color: "#5856D6",
  },
  {
    id: "nouns",
    title: "Nouns",
    subtitle: "People, places, and things",
    icon: "📦",
    color: "#FF9500",
  },
  {
    id: "verbs",
    title: "Verbs",
    subtitle: "Actions and movement",
    icon: "⚡",
    color: "#FF2D55",
  },
  {
    id: "adjectives",
    title: "Adjectives",
    subtitle: "Describe the world",
    icon: "✨",
    color: "#AF52DE",
  },
  {
    id: "colors",
    title: "Colors",
    subtitle: "Name every shade",
    icon: "🎨",
    color: "#FF3B30",
  },
  {
    id: "maths",
    title: "Maths",
    subtitle: "Numbers, counting, and quantities",
    icon: "🔢",
    color: "#30B0C7",
  },
  {
    id: "time",
    title: "Time",
    subtitle: "Days, clocks, and calendars",
    icon: "⏰",
    color: "#64D2FF",
  },
  {
    id: "emotions",
    title: "Emotions",
    subtitle: "Feelings and expressions",
    icon: "💭",
    color: "#FF6482",
  },
  {
    id: "body",
    title: "Body Parts",
    subtitle: "Head to toe vocabulary",
    icon: "🧍",
    color: "#AC8E68",
  },
  {
    id: "senses",
    title: "Senses",
    subtitle: "See, hear, touch, taste, smell",
    icon: "👁️",
    color: "#5AC8FA",
  },
  {
    id: "clothing",
    title: "Clothing",
    subtitle: "What we wear",
    icon: "👕",
    color: "#FF9F0A",
  },
  {
    id: "food",
    title: "Food & Drinks",
    subtitle: "Meals, snacks, and beverages",
    icon: "🍽️",
    color: "#FF6B00",
  },
  {
    id: "animals",
    title: "Animals",
    subtitle: "Creatures great and small",
    icon: "🐾",
    color: "#32ADE6",
  },
  {
    id: "furniture",
    title: "Furniture",
    subtitle: "Rooms and household items",
    icon: "🪑",
    color: "#8E8E93",
  },
  {
    id: "occupations",
    title: "Occupations",
    subtitle: "Jobs and workplaces",
    icon: "💼",
    color: "#007AFF",
  },
  {
    id: "school",
    title: "School",
    subtitle: "Classroom language",
    icon: "📚",
    color: "#5856D6",
  },
  {
    id: "travel",
    title: "Travel & Directions",
    subtitle: "Getting around and finding places",
    icon: "🧭",
    color: "#34C759",
  },
  {
    id: "countries",
    title: "Countries",
    subtitle: "Nations and nationalities",
    icon: "🌍",
    color: "#30B0C7",
  },
  {
    id: "culture",
    title: "Culture",
    subtitle: "Customs, values, and community",
    icon: "🎭",
    color: "#AF52DE",
  },
  {
    id: "medical",
    title: "Medical",
    subtitle: "Health and the clinic",
    icon: "🩺",
    color: "#FF2D55",
  },
  {
    id: "politics",
    title: "Politics",
    subtitle: "Government and civic life",
    icon: "🏛️",
    color: "#1D1D1F",
  },
  {
    id: "technology",
    title: "Technology",
    subtitle: "Devices and the digital world",
    icon: "💻",
    color: "#64D2FF",
  },
  {
    id: "psychology",
    title: "Psychology",
    subtitle: "Mind, behavior, and wellbeing",
    icon: "🧠",
    color: "#BF5AF2",
  },
  {
    id: "speaking",
    title: "Speaking / Signing",
    subtitle: "Conversation fluency practice",
    icon: "💬",
    color: "#007AFF",
  },
  {
    id: "reading",
    title: "Reading",
    subtitle: "Decode written and signed text",
    icon: "📖",
    color: "#FF9500",
  },
  {
    id: "writing",
    title: "Writing",
    subtitle: "Compose clear sentences",
    icon: "✍️",
    color: "#FF6B00",
  },
  {
    id: "translating",
    title: "Translating",
    subtitle: "Move meaning between languages",
    icon: "🔄",
    color: "#5856D6",
  },
  {
    id: "slang",
    title: "Slang & Cursing",
    subtitle: "Informal register (use carefully)",
    icon: "🙊",
    color: "#FF3B30",
  },
  {
    id: "quotes",
    title: "Quotes & Sayings",
    subtitle: "Proverbs and memorable lines",
    icon: "💬",
    color: "#AF52DE",
  },
  {
    id: "media",
    title: "TV, Movies & Books",
    subtitle: "Stories, screens, and titles",
    icon: "🎬",
    color: "#FF2D55",
  },
];

export function getUnit(id: string): UnitDef | undefined {
  return UNITS.find((u) => u.id === id);
}
