import type { LanguageId, UnitDef, UnitId } from "./types";
import { UNIT_CEFR } from "./cefr";

/** Pedagogical order: foundations → words → daily life → society → skills → media (A1→C2). */
export const UNITS: UnitDef[] = [
  {
    id: "grammar",
    title: "Grammar",
    subtitle: "Word order — learn how to arrange sentences",
    icon: "📐",
    color: "#FF2D95",
    cefr: UNIT_CEFR.grammar,
  },
  {
    id: "alphabet",
    title: "Alphabet & Sounds",
    subtitle: "Letters, fingerspelling, and phonetics",
    icon: "🔤",
    color: "#34C759",
    cefr: UNIT_CEFR.alphabet,
  },
  {
    id: "pronouns",
    title: "Pronouns",
    subtitle: "I, you, we, they — and pointing",
    icon: "👆",
    color: "#5856D6",
    cefr: UNIT_CEFR.pronouns,
  },
  {
    id: "nouns",
    title: "Nouns",
    subtitle: "People, places, and things",
    icon: "📦",
    color: "#FF9500",
    cefr: UNIT_CEFR.nouns,
  },
  {
    id: "verbs",
    title: "Verbs",
    subtitle: "Actions and movement",
    icon: "⚡",
    color: "#FF2D55",
    cefr: UNIT_CEFR.verbs,
  },
  {
    id: "adjectives",
    title: "Adjectives",
    subtitle: "Describe the world",
    icon: "✨",
    color: "#AF52DE",
    cefr: UNIT_CEFR.adjectives,
  },
  {
    id: "colors",
    title: "Colors",
    subtitle: "Name every shade",
    icon: "🎨",
    color: "#FF3B30",
    cefr: UNIT_CEFR.colors,
  },
  {
    id: "maths",
    title: "Maths",
    subtitle: "Numbers, counting, and quantities",
    icon: "🔢",
    color: "#30B0C7",
    cefr: UNIT_CEFR.maths,
  },
  {
    id: "time",
    title: "Time",
    subtitle: "Days, clocks, and calendars",
    icon: "⏰",
    color: "#64D2FF",
    cefr: UNIT_CEFR.time,
  },
  {
    id: "emotions",
    title: "Emotions",
    subtitle: "Feelings and expressions",
    icon: "💭",
    color: "#FF6482",
    cefr: UNIT_CEFR.emotions,
  },
  {
    id: "body",
    title: "Body Parts",
    subtitle: "Head to toe vocabulary",
    icon: "🧍",
    color: "#AC8E68",
    cefr: UNIT_CEFR.body,
  },
  {
    id: "senses",
    title: "Senses",
    subtitle: "See, hear, touch, taste, smell",
    icon: "👁️",
    color: "#5AC8FA",
    cefr: UNIT_CEFR.senses,
  },
  {
    id: "clothing",
    title: "Clothing",
    subtitle: "What we wear",
    icon: "👕",
    color: "#FF9F0A",
    cefr: UNIT_CEFR.clothing,
  },
  {
    id: "food",
    title: "Food & Drinks",
    subtitle: "Meals, snacks, and beverages",
    icon: "🍽️",
    color: "#FF6B00",
    cefr: UNIT_CEFR.food,
  },
  {
    id: "animals",
    title: "Animals",
    subtitle: "Creatures great and small",
    icon: "🐾",
    color: "#32ADE6",
    cefr: UNIT_CEFR.animals,
  },
  {
    id: "furniture",
    title: "Furniture",
    subtitle: "Rooms and household items",
    icon: "🪑",
    color: "#8E8E93",
    cefr: UNIT_CEFR.furniture,
  },
  {
    id: "occupations",
    title: "Occupations",
    subtitle: "Jobs and workplaces",
    icon: "💼",
    color: "#FF2D95",
    cefr: UNIT_CEFR.occupations,
  },
  {
    id: "school",
    title: "School",
    subtitle: "Classroom language",
    icon: "📚",
    color: "#5856D6",
    cefr: UNIT_CEFR.school,
  },
  {
    id: "travel",
    title: "Travel & Directions",
    subtitle: "Getting around and finding places",
    icon: "🧭",
    color: "#34C759",
    cefr: UNIT_CEFR.travel,
  },
  {
    id: "countries",
    title: "Countries",
    subtitle: "Nations and nationalities",
    icon: "🌍",
    color: "#30B0C7",
    cefr: UNIT_CEFR.countries,
  },
  {
    id: "culture",
    title: "Culture",
    subtitle: "Customs, values, and community",
    icon: "🎭",
    color: "#AF52DE",
    cefr: UNIT_CEFR.culture,
  },
  // ——— Language specialty units (filtered per path) ———
  {
    id: "handshapes",
    title: "Handshapes",
    subtitle: "Classifier handshapes that stand for things in space",
    icon: "✋",
    color: "#FF2D95",
    cefr: UNIT_CEFR.handshapes,
    languages: ["asl", "bsl", "isl", "nzsl"],
  },
  {
    id: "nonmanuals",
    title: "Non-manuals",
    subtitle: "Face, brows, and head movement that carry grammar",
    icon: "😮",
    color: "#5856D6",
    cefr: UNIT_CEFR.nonmanuals,
    languages: ["asl", "bsl", "isl", "nzsl"],
  },
  {
    id: "deafculture",
    title: "Deaf Culture",
    subtitle: "Community values, etiquette, and identity",
    icon: "🤟",
    color: "#1D1D1F",
    cefr: UNIT_CEFR.deafculture,
    languages: ["asl", "bsl", "isl", "nzsl"],
  },
  {
    id: "tones",
    title: "Tones",
    subtitle: "The four tones that change meaning",
    icon: "🎵",
    color: "#FF3B30",
    cefr: UNIT_CEFR.tones,
    languages: ["mandarin"],
  },
  {
    id: "characters",
    title: "Characters",
    subtitle: "Radicals, strokes, and reading hanzi",
    icon: "漢",
    color: "#FF9500",
    cefr: UNIT_CEFR.characters,
    languages: ["mandarin"],
  },
  {
    id: "measurewords",
    title: "Measure Words",
    subtitle: "Classifiers between numbers and nouns",
    icon: "🔢",
    color: "#30B0C7",
    cefr: UNIT_CEFR.measurewords,
    languages: ["mandarin"],
  },
  {
    id: "cases",
    title: "Cases",
    subtitle: "Nominative, accusative, and the rest",
    icon: "⚖️",
    color: "#AF52DE",
    cefr: UNIT_CEFR.cases,
    languages: ["latin"],
  },
  {
    id: "declensions",
    title: "Declensions",
    subtitle: "Noun ending patterns by stem class",
    icon: "📜",
    color: "#5856D6",
    cefr: UNIT_CEFR.declensions,
    languages: ["latin"],
  },
  {
    id: "conjugations",
    title: "Conjugations",
    subtitle: "Verb endings across persons and tenses",
    icon: "🔀",
    color: "#FF2D55",
    cefr: UNIT_CEFR.conjugations,
    languages: ["latin"],
  },
  {
    id: "serestar",
    title: "Ser & Estar",
    subtitle: "Two ways to say “to be”",
    icon: "🪞",
    color: "#FF6B00",
    cefr: UNIT_CEFR.serestar,
    languages: ["spanish"],
  },
  {
    id: "formality",
    title: "Tú & Usted",
    subtitle: "Formal and informal address",
    icon: "🎩",
    color: "#5856D6",
    cefr: UNIT_CEFR.formality,
    languages: ["spanish"],
  },
  {
    id: "subjunctive",
    title: "Subjunctive",
    subtitle: "Mood for wishes, doubts, and emotion",
    icon: "💫",
    color: "#AF52DE",
    cefr: UNIT_CEFR.subjunctive,
    languages: ["spanish"],
  },
  {
    id: "dutcharticles",
    title: "De & Het",
    subtitle: "Common vs neuter articles",
    icon: "📰",
    color: "#FF9500",
    cefr: UNIT_CEFR.dutcharticles,
    languages: ["dutch"],
  },
  {
    id: "separable",
    title: "Separable Verbs",
    subtitle: "Prefixes that split off in main clauses",
    icon: "✂️",
    color: "#FF2D55",
    cefr: UNIT_CEFR.separable,
    languages: ["dutch"],
  },
  {
    id: "particles",
    title: "Particles",
    subtitle: "kei te, i, ka — tense and aspect markers",
    icon: "🧩",
    color: "#34C759",
    cefr: UNIT_CEFR.particles,
    languages: ["maori"],
  },
  {
    id: "pepeha",
    title: "Pepeha",
    subtitle: "Introduce yourself through place and people",
    icon: "🏔️",
    color: "#30B0C7",
    cefr: UNIT_CEFR.pepeha,
    languages: ["maori"],
  },
  {
    id: "marae",
    title: "Marae",
    subtitle: "Protocol, roles, and sacred spaces",
    icon: "🏛️",
    color: "#AC8E68",
    cefr: UNIT_CEFR.marae,
    languages: ["maori"],
  },
  {
    id: "medical",
    title: "Medical",
    subtitle: "Health and the clinic",
    icon: "🩺",
    color: "#FF2D55",
    cefr: UNIT_CEFR.medical,
  },
  {
    id: "politics",
    title: "Politics",
    subtitle: "Government and civic life",
    icon: "🏛️",
    color: "#1D1D1F",
    cefr: UNIT_CEFR.politics,
  },
  {
    id: "technology",
    title: "Technology",
    subtitle: "Devices and the digital world",
    icon: "💻",
    color: "#64D2FF",
    cefr: UNIT_CEFR.technology,
  },
  {
    id: "psychology",
    title: "Psychology",
    subtitle: "Mind, behavior, and wellbeing",
    icon: "🧠",
    color: "#BF5AF2",
    cefr: UNIT_CEFR.psychology,
  },
  {
    id: "speaking",
    title: "Speaking / Signing",
    subtitle: "Conversation fluency practice",
    icon: "💬",
    color: "#FF2D95",
    cefr: UNIT_CEFR.speaking,
  },
  {
    id: "reading",
    title: "Reading",
    subtitle: "Decode written and signed text",
    icon: "📖",
    color: "#FF9500",
    cefr: UNIT_CEFR.reading,
  },
  {
    id: "writing",
    title: "Writing",
    subtitle: "Compose clear sentences",
    icon: "✍️",
    color: "#FF6B00",
    cefr: UNIT_CEFR.writing,
  },
  {
    id: "translating",
    title: "Translating",
    subtitle: "Move meaning between languages",
    icon: "🔄",
    color: "#5856D6",
    cefr: UNIT_CEFR.translating,
  },
  {
    id: "slang",
    title: "Slang & Cursing",
    subtitle: "Informal register (use carefully)",
    icon: "🙊",
    color: "#FF3B30",
    cefr: UNIT_CEFR.slang,
  },
  {
    id: "quotes",
    title: "Quotes & Sayings",
    subtitle: "Proverbs and memorable lines",
    icon: "💬",
    color: "#AF52DE",
    cefr: UNIT_CEFR.quotes,
  },
  {
    id: "media",
    title: "TV, Movies & Books",
    subtitle: "Stories, screens, and titles",
    icon: "🎬",
    color: "#FF2D55",
    cefr: UNIT_CEFR.media,
  },
];

export function getUnit(id: string): UnitDef | undefined {
  return UNITS.find((u) => u.id === id);
}

/** Shared + language-specific units for a learning path. */
export function getUnitsForLanguage(languageId: LanguageId): UnitDef[] {
  return UNITS.filter(
    (unit) => !unit.languages || unit.languages.includes(languageId),
  );
}

export function isUnitForLanguage(
  unitId: UnitId,
  languageId: LanguageId,
): boolean {
  const unit = getUnit(unitId);
  if (!unit) return false;
  return !unit.languages || unit.languages.includes(languageId);
}
